## Quiz Analysis: Pilot and Main Study


```{r, include=FALSE}
library("here")
library("tidyverse")
library("rlang")
library("gt")
library("patchwork")
library("ggtext")
```

### Pilot Quiz Results

```{r include=FALSE, warning=FALSE, echo=FALSE}
pilot_2_dfs <- readRDS(file = here("_data", "_participant_scores", "wave_2", "pilot_2_dfs.RDS"))


# subset pilot dfs
quiz_dfs <- lapply(pilot_2_dfs, function(df){
 
  df |>
    select(participant_ID, 
           Quiz1_1, Quiz2_1, Quiz3_1, 
           Quiz1, Quiz2, Quiz3) |>
    
    unique() |>
    
    # recalculate Quiz 3
    mutate(Quiz3 = case_when(
      Quiz3_1 == "-1" | Quiz3_1 == "0" | Quiz3_1 == "1"  ~ "1", 
      .default = "0")) |>
    
    # convert to numeric
    mutate(
      Quiz1 = as.numeric(Quiz1), 
      Quiz2 = as.numeric(Quiz2), 
      Quiz3 = as.numeric(Quiz3)) |>
    
    mutate(
      Quiz1_1 = ifelse(is.na(Quiz1_1), "NA", as.character(Quiz1_1)),
      Quiz1_1 = factor(Quiz1_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      Quiz2_1 = ifelse(is.na(Quiz2_1), "NA", as.character(Quiz2_1)),
      Quiz2_1 = factor(Quiz2_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      Quiz3_1 = ifelse(is.na(Quiz3_1), "NA", as.character(Quiz3_1)),
      Quiz3_1 = factor(Quiz3_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE)
)})

df <- bind_rows(quiz_dfs, .id = "Pilot")
```

```{r include=FALSE}
apa_theme <-
  theme_classic(base_size = 12, base_family = "sans") +
  theme(
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 10),
    legend.position = "bottom",
    legend.title = element_text(size = 11),
    legend.text  = element_text(size = 10),
    panel.border = element_blank(),
    axis.line = element_line(color = "black"),
    strip.background = element_blank(),
    strip.text = element_text(size = 11)
  )
```


```{r include=FALSE}
plot_bars <- function(df, column1, column2, option) {
  
  df |> 
    mutate({{column2}} := fct_recode(as.factor({{column2}}), 
                                     "Correct"   = "1","Incorrect" = "0")) |>
        
    ggplot(aes({{column1}}, fill = as.factor({{column2}}))) + 
    geom_bar() +
    scale_fill_viridis_d(option = option,
                         name = "Response:") +
    
    scale_y_continuous(limits = c(0, 225)) +
    
    scale_x_discrete(drop = FALSE)}
```

```{r}
p1 <- plot_bars(df, Quiz1_1, Quiz1, option = "D") +
  xlab("Q1 Responses") + ylab("Count") +
  apa_theme

p2 <- plot_bars(df, Quiz2_1, Quiz2, option = "D") +
  xlab("Q2 Responses") + ylab("Count") +
  apa_theme

p3 <- plot_bars(df, Quiz3_1, Quiz3, option = "D") +
  xlab("Q3 Responses") + ylab("") +
  apa_theme

pilot_quiz_correctness_plot <- (p1 | p2 | p3) +
  plot_layout(guides = "collect") &     
  theme(legend.position = "bottom", 
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

pilot_quiz_correctness_plot

#ggsave(here("images", "pilot_quiz_correctness.pdf"))
```



```{r include=FALSE, warning=FALSE, echo=FALSE}
#pilot_2_dfs <- readRDS(file = here("_data", "_participant_scores", "wave_2", "pilot_2_dfs.RDS"))


# subset pilot dfs
quiz_dfs <- lapply(pilot_2_dfs, function(df){
 
  df |>
    select(participant_ID, 
           Quiz1_1, Quiz2_1, Quiz3_1, 
           Quiz1, Quiz2, Quiz3) |>
    
    unique() |>
    
    # recalculate Quiz 3
    mutate(Quiz3 = case_when(
      Quiz3_1 == "-1" | Quiz3_1 == "0" | Quiz3_1 == "1"  ~ "1", 
      .default = "0")) |>
    
    # convert to numeric
    mutate(
      Quiz1 = as.numeric(Quiz1), 
      Quiz2 = as.numeric(Quiz2), 
      Quiz3 = as.numeric(Quiz3)) |>
    
    mutate(
      Quiz1_1 = ifelse(is.na(Quiz1_1), "NA", as.character(Quiz1_1)),
      Quiz1_1 = factor(Quiz1_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      Quiz2_1 = ifelse(is.na(Quiz2_1), "NA", as.character(Quiz2_1)),
      Quiz2_1 = factor(Quiz2_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      Quiz3_1 = ifelse(is.na(Quiz3_1), "NA", as.character(Quiz3_1)),
      Quiz3_1 = factor(Quiz3_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE)
)})

df <- bind_rows(quiz_dfs, .id = "Pilot")
```

```{r}
summarize_study <- function(df) {
  df %>%
    summarise(
      Q1 = sprintf("%d (%.1f%%)", sum(Quiz1, na.rm = TRUE),
                      mean(Quiz1, na.rm = TRUE) * 100),
      Q2 = sprintf("%d (%.1f%%)", sum(Quiz2, na.rm = TRUE),
                      mean(Quiz2, na.rm = TRUE) * 100),
      Q3 = sprintf("%d (%.1f%%)", sum(Quiz3, na.rm = TRUE),
                      mean(Quiz3, na.rm = TRUE) * 100)) %>%
    
    pivot_longer(everything(), names_to = "Question", values_to = "N_percent")
}

table <- lapply(quiz_dfs, summarize_study) %>%
  
  bind_rows(.id = "Study") %>%
  
  pivot_wider(names_from = Study, values_from = N_percent) %>%
  
  gt() %>%

  cols_label(
    Question = "Item",
    lyrics = "Pilot: Lyrics",
    speeches1 = "Pilot: Speeches 1",
    speeches2 = "Pilot: Speeches 2"
  ) %>%
  cols_align(
    align = "center",
    columns = everything()
  ) %>%
  cols_width(everything() ~ px(100))

table

gtsave(table, here("tables", "pilot_quiz_correctness.tex"))

rm(summarize_study)
```

```{r include=FALSE}
apa_theme <-
  theme_classic(base_size = 12, base_family = "sans") +
  theme(
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 10),
    legend.position = "bottom",
    legend.title = element_text(size = 11),
    legend.text  = element_text(size = 10),
    panel.border = element_blank(),
    axis.line = element_line(color = "black"),
    strip.background = element_blank(),
    strip.text = element_text(size = 11)
  )
```


```{r echo=FALSE}
plot_stacked_bars <- function(df, column, option) {
  
  df |>
    ggplot(aes({{column}}, fill = as.factor(Pilot))) + 
    geom_bar() +
    scale_fill_viridis_d(
      option = option,
      name = "Pilot Study: ",
      labels = c("lyrics" = "Lyrics", 
                 "speeches1"  = "Speeches #1", 
                 "speeches2"  = "Speeches #2")) +
    scale_y_continuous(limits = c(0, 225)) +
    scale_x_discrete(drop = FALSE)
}
```

```{r}
p1 <- plot_stacked_bars(df, Quiz1_1, option = "C") +
  xlab("Q1 Responses") + ylab("Count") +
  apa_theme

p2 <- plot_stacked_bars(df, Quiz2_1, option = "C") +
  xlab("Q2 Responses") + ylab("") +
  apa_theme

p3 <- plot_stacked_bars(df, Quiz3_1, option = "C") +
  xlab("Q3 Responses") + ylab("") +
  apa_theme

(p1 | p2 | p3) +
    plot_layout(guides = "collect") &
    theme(legend.position = "bottom", 
          plot.title = element_markdown(hjust = 0), 
          plot.subtitle = element_markdown(hjust = 0), 
          plot.caption = element_markdown(hjust = 0))

ggsave(here("images", "pilot_quiz_correctness_by_study.pdf"))
```

### Main Study Quiz Results

```{r, include=FALSE}
data_path <- here("_data", "_participant_scores", "wave_2")

# read in data
wave_2_dfs <- readRDS(here(data_path, "wave_2_dfs.RDS"))

# subset each df
wave_2_demog_dfs <- lapply(wave_2_dfs, function(df){
  df <- df |> select(participant_ID, Age, Sex, `Ethnicity`) |> unique()})

# bring back spectrum
for (name in c("speeches1", "speeches2")) {
  wave_2_demog_dfs[[name]] <- merge(
    wave_2_demog_dfs[[name]],
    wave_2_dfs[[name]] |> 
      dplyr::select(participant_ID, `Political spectrum (us)`) |> unique(),
    by = "participant_ID")}

rm(wave_2_dfs)

# convert age to numeric
wave_2_demog_dfs <- lapply(wave_2_demog_dfs, function(df){df|>mutate(Age = as.numeric(Age))})

# recode Asian ethnicity
wave_2_demog_dfs <- lapply(wave_2_demog_dfs, function(df){
  df |> mutate(Ethnicity = case_when(
    Ethnicity == "East Asian" | Ethnicity == "South East Asian" | Ethnicity == "South Asian" ~ "Asian", 
    .default = Ethnicity))})

wave_labels <- c(
  lyrics1   = "Main 1 (Lyrics 1)",
  lyrics2   = "Main 2 (Lyrics 2)",
  speeches1 = "Main 3 (Speeches 1)",
  speeches2 = "Main 4 (Speeches 2)"
)
```

```{r, include=FALSE}
quiz_df <- readRDS(here("_data", "_participant_scores", "wave_2", "wave_2_quiz_df.RDS"))

quiz_df <- quiz_df |>
  
    select(-Ethnicity) |> 
  
    # convert to numeric
    mutate(
      Quiz_1 = as.numeric(Quiz_1), 
      Quiz_2 = as.numeric(Quiz_2), 
      Quiz_3 = as.numeric(Quiz_3)) |>
    
    # set as ordered factors
    mutate(
      Quiz1 = ifelse(is.na(Quiz1), "NA", as.character(Quiz1)),
      Quiz1 = factor(Quiz1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      
      Quiz2 = ifelse(is.na(Quiz2), "NA", as.character(Quiz2)),
      Quiz2 = factor(Quiz2, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      
      Quiz3 = ifelse(is.na(Quiz3), "NA", as.character(Quiz3)),
      Quiz3 = factor(Quiz3, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE)) |>
  
  rename(Study = wave)
```

```{r include=FALSE}
summarize_study <- function(df) {
  df %>%
    summarise(
      Q1 = sprintf("%d (%.1f%%)", sum(Quiz_1, na.rm = TRUE),
                      mean(Quiz_1, na.rm = TRUE) * 100),
      Q2 = sprintf("%d (%.1f%%)", sum(Quiz_2, na.rm = TRUE),
                      mean(Quiz_2, na.rm = TRUE) * 100),
      Q3 = sprintf("%d (%.1f%%)", sum(Quiz_3, na.rm = TRUE),
                      mean(Quiz_3, na.rm = TRUE) * 100)
    ) %>%
    
    pivot_longer(everything(), names_to = "Question", values_to = "N_percent")
}
```

```{r}
# create a list of dataframes, one for each study
quiz_dfs <- split.data.frame(quiz_df, quiz_df$Study)


table <- lapply(quiz_dfs, summarize_study) %>%
  
  bind_rows(.id = "Study") %>%
  
  pivot_wider(names_from = Study, values_from = N_percent) %>%
  
  gt() %>%
  
  cols_label(
    Question = "Item",
    lyrics_1 = "Wave: Lyrics 1",
    lyrics_2 = "Wave: Lyrics 2",
    speeches_1 = "Wave: Speeches 1",
    speeches_2 = "Wave: Speeches 2"
  ) %>%
  cols_align(
    align = "center",
    columns = everything()
  ) %>%
  cols_width(everything() ~ px(100))

table

gtsave(table, here("tables", "main_quiz_correctness.tex"))

rm(table, quiz_dfs)
```


```{r}
plot_bars <- function(df, 
                      column1, # responses
                      column2, # color
                      option) {
  
  df |> 
    mutate({{column2}} := fct_recode(as.factor({{column2}}), 
                                     "Correct"   = "1","Incorrect" = "0")) |>
        
    ggplot(aes({{column1}}, fill = as.factor({{column2}}))) + 
    geom_bar() +
    scale_fill_viridis_d(option = option,
                         name = "Response:") +
    scale_y_continuous(limits = c(0, 1250)) +
    
    scale_x_discrete(drop = FALSE)}
```

```{r}
# including those that were screened out
df <- quiz_df

p1 <- plot_bars(df, Quiz1, Quiz_1, option = "D") +
  xlab("Q1 Responses") + ylab("Count") +
  apa_theme

p2 <- plot_bars(df, Quiz2, Quiz_2, option = "D") +
  xlab("Q2 Responses") + ylab("Count") +
  apa_theme

p3 <- plot_bars(df, Quiz3, Quiz_3, option = "D") +
  xlab("Q3 Responses") + ylab("") +
  apa_theme

(p1 | p2 | p3) +
  plot_layout(guides = "collect") &     
  theme(legend.position = "bottom", 
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

ggsave(here("images", "main_quiz_correctness.pdf"))
```
