project:
  title: "values_from_text"
  type: website
  output-dir: docs  
  resources:
    - images/

bibliography: references.bib
csl: apa.csl

website:
  title: "Estimating Personal Values in Text"
  navbar:
    left:
      - href: manuscript.qmd
        text: Manuscript
      

format:
  html:
    toc: true
    number-sections: false
    code-fold: true
    css: styles.css
  docx:
    toc: false
    number-sections: false
    output-file: manuscript.docx
