project:
  title: "values_from_text"
  type: website
  output-dir: docs  
  resources:
    - images/

bibliography: references.bib
csl: apa.csl

execute:
  cache: false
  freeze: auto

knitr:
  opts_chunk:
    fig.path: "docs/images/"

website:
  title: "Estimating Personal Values in Text"
  navbar:
    left:
      - href: manuscript.qmd
        text: Manuscript
      
format:
  html:
    toc: true
    number-sections: false
    code-fold: true
    css: styles.css
  pdf:
    output-file: manuscript.pdf
    documentclass: apa7
    classoption:
      - man
    keep-tex: true

