project:
  title: "values_from_text"
  type: website
  output-dir: docs

bibliography: references.bib
csl: apa.csl

website:
  title: "Estimating Personal Values in Text"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    number-sections: true
  docx:
    toc: true
    number-sections: true
