## Pilot Results

```{r include=FALSE}
library('here')       # file logistics
library("tidyverse")  # code logistics
library("patchwork")  # merge plots
library("gt")         # markdown
library("rlang")
library("ggtext")     # text plots
library("lme4")
library("lmerTest")
library("emmeans")

values <- c("POWER", "ACHIEVEMENT", "HEDONISM",  
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION",  
            "CONFORMITY", "SECURITY")
```

```{r include=FALSE} 
# read in data
pilot_2_dfs <- readRDS(here("_data", "_participant_scores", "wave_2", "pilot_2_dfs.RDS"))

# merge ethnicity (Prolific has 3 separate US Asian Ethnicity categories)
pilot_2_dfs[['lyrics']] <- pilot_2_dfs[['lyrics']] %>%
  mutate(ethnicity = case_when(
    Ethnicity == "South East Asian" ~ "Asian", 
    Ethnicity == "South Asian" ~ "Asian", 
    Ethnicity == "East Asian" ~ "Asian", 
    .default = Ethnicity))

pilot_2_dfs[['speeches1']] <- pilot_2_dfs[['speeches1']] %>%
    mutate(ethnicity = case_when(
    Ethnicity == "South East Asian" ~ "Asian", 
    Ethnicity == "South Asian" ~ "Asian", 
    Ethnicity == "East Asian" ~ "Asian", 
    .default = Ethnicity))

pilot_2_dfs[['speeches2']] <- pilot_2_dfs[['speeches2']] |> 
  mutate(spectrum = `Political spectrum (us)`)
```

```{r}
df <- pilot_2_dfs$lyrics |> 
  select(participant_ID, item_ID, Ethnicity, all_of(values)) |> 
  pivot_longer(cols = all_of(values), names_to = "value", values_to = "rating")

mod <- lmer(rating ~ value * Ethnicity + (1|participant_ID) + (1|item_ID), data = df)

anova(mod)

emm_ethnicity <- emmeans(mod, ~ Ethnicity)

plot(emm_ethnicity, comparisons = T) + theme_minimal()

df <- pilot_2_dfs$speeches1 |> 
  select(participant_ID, item_ID, Ethnicity, all_of(values)) |> 
  pivot_longer(cols = all_of(values), names_to = "value", values_to = "rating")

mod <- lmer(rating ~ value * Ethnicity + (1|participant_ID) + (1|item_ID), data = df)

anova(mod)

emm_ethnicity <- emmeans(mod, ~ Ethnicity)

plot(emm_ethnicity, comparisons = T) + theme_minimal()
```

```{r}
df <- pilot_2_dfs$speeches2 |> 
  select(participant_ID, item_ID, spectrum, all_of(values)) |> 
  pivot_longer(cols = all_of(values), names_to = "value", values_to = "rating")

mod <- lmer(rating ~ value * spectrum + (1|participant_ID) + (1|item_ID), data = df)

anova(mod)

emm_spectrum <- emmeans(mod, ~ spectrum)

plot(emm_spectrum, comparisons = T) + theme_minimal()
```

