---
title: "reliability_comparison"
author: "Andrew M. Demetriou"
---

```{r}
library("here")
library("tidyverse")
library("cowplot")
```

```{r}
file_path <- here("_data", "_intermediary_data")

ethnicity_subsample_ICC_dfs <- readRDS(file = here(file_path, "wave_2_subsample_ethnicity_ICC_dfs.RDS"))
spectrum_subsample_ICC_dfs <- readRDS(file = here(file_path, "wave_2_subsample_spectrum_ICC_dfs.RDS"))
```

```{r}
plot_summary_by_metric <- function(df, metric, metric_lower, metric_upper, text, option) {
  
  subsets <- as.list(df$subset%>%unique())
  
  lapply(subsets, function(sub){
    
    df %>%
      filter(subset == sub) %>%
      ggplot(aes(y=value, x={{metric}}, color = value)) +
      geom_point() +
      geom_errorbar(aes(xmin = {{metric_lower}}, xmax = {{metric_upper}})) +
      theme_minimal() +
      xlim(-.5, 1) +
      geom_vline(xintercept = 0.75, color = "red", size = .2 ) +
      scale_color_viridis_d(option = option) +
      theme(legend.position="none") +
      ggtitle(paste0(text, ":", sub))
    })
  }
```

```{r}
# compute plots
wave_2_lyrics_agreement_plots <- plot_summary_by_metric(ethnicity_subsample_ICC_dfs[[1]], ICC2k, ICC2k_lower, ICC2k_upper, "lyrics", option = "plasma")

wave_2_speeches1_agreement_plots <- plot_summary_by_metric(ethnicity_subsample_ICC_dfs[[2]], ICC2k, ICC2k_lower, ICC2k_upper, "speeches", option = "D")

wave_2_speeches2_agreement_plots <- plot_summary_by_metric(spectrum_subsample_ICC_dfs, ICC2k, ICC2k_lower, ICC2k_upper, "speeches", option = "D")
```

# todo: (1) extract subset plots for appendix
# todo: (2) extract overall plots and merge for main paper
# todo: (3) naming convention, and pdf format


```{r}
plots <- wave_2_lyrics_agreement_plots
plot_grid(
  plots[[1]]+xlim(.5, 1), #overall
  plot_grid(plots[[2]], plots[[3]], plots[[4]], plots[[5]]), #by ethnicity
  ncol = 1)
ggsave(here("images", "wave_lyrics_reliability_by_value_by_ethnicity.pdf"),
       dpi = "retina", height=8.5)

plots <- wave_2_speeches1_agreement_plots
plot_grid(
  plots[[1]], #overall
  plot_grid(plots[[2]], plots[[3]], plots[[4]], plots[[5]]), #by ethnicity
  ncol = 1)
ggsave(here("images", "wave_speeches_reliability_by_value_by_ethnicity.pdf"),
       dpi = "retina", height=8.5)

plots <- wave_2_speeches2_agreement_plots
plot_grid(
  plots[[1]], #overall
  plot_grid(plots[[2]], plots[[3]], plots[[4]]), #by ethnicity
  ncol = 1)
ggsave(here("images", "wave_speeches_reliability_by_value_by_spectrum.pdf"),
       dpi = "retina", height=8.5)
```
