## Survey Flow

```{r}
library(DiagrammeR)     # flow charts
library(DiagrammeRsvg)  # convert flow chart to svg
library(rsvg)           # convert svg to other formats
library(here)           # file logistics

images_path <- here("images")
```


```{r fig.align="center", out.width="80%", echo=FALSE, message=FALSE, warning=FALSE}
diagram <- grViz("
digraph survey_flow {
  graph [layout = dot, rankdir = TB]

  node [shape = box, style = filled, fontname = Helvetica, fontsize = 20, width=2.5, fixedsize=false]

  # Main vertical flow
  Consent -> SSVS -> General_Instructions -> Quiz -> Final_Instructions -> Randomizer1 -> AttentionCheck -> Randomizer2 -> Debrief -> Prolific3

  # Node colors
  Consent [fillcolor = gainsboro]
  SSVS [fillcolor = lightblue]
  General_Instructions [label = \"General Instructions\", fillcolor = gainsboro]
  Quiz [label = \"Comprehension Quiz\", fillcolor = gainsboro]
  Final_Instructions [label = \"Final Instructions\", fillcolor = gainsboro]
  Randomizer1 [label = \"Randomizer:\\n 7 Items\", fillcolor = thistle1]
  Randomizer2 [label = \"Randomizer:\\n 7 Items\", fillcolor = thistle1]
  AttentionCheck [fillcolor = gainsboro]
  Debrief [fillcolor = gainsboro]
  Prolific3 [label = \"Prolific:\\n End of Survey\", fillcolor = mistyrose]
}
")

diagram
```

```{r}
# Export as SVG
svg <- export_svg(diagram)

# Convert to PNG
rsvg_png(charToRaw(svg), file = here(images_path, "survey_flow.png"), width = 1200)
```

