---
title: "R Notebook"
---

```{r}
library("here")         # file logistics
library("lme4")         # mixed effects metric
library("lmerTest")     # p values
library("ordinal")      # mixed effects ordinal
library("tidyverse")    # code logistics
library("performance")  # model performance for lmer
library("emmeans")      # estimated marginal means
library("cowplot")      # merge plots

# Schwartz value inventory
values <- c("POWER", "ACHIEVEMENT", "HEDONISM",  
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION",  
            "CONFORMITY", "SECURITY")

# TO "CENTER" CATEGORICAL PREDICTORS, set the coding to contr.sum (deviations from the average)
options(scipen = 999, contrasts = c("contr.sum", "contr.poly"))
```


```{r}
# read in data
wave_1_dfs <- readRDS(here("_data", "_intermediary_data", "wave_1_dfs.RDS"))
wave_2_dfs <- readRDS(here("_data", "_intermediary_data", "wave_2_dfs.RDS"))

# read in likert models
wave_1_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_1_mods.RDS"))
wave_2_lyrics_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_lyrics_mods.RDS"))
wave_2_speeches_ethnicity_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_ethnicity_mods.RDS"))
wave_2_speeches_spectrum_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_spectrum_mods.RDS"))

# read in lowres models
wave_2_lyrics_lowres_mods  <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_lyrics_lowres_mods.RDS"))
wave_2_speeches_ethnicity_lowres_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_ethnicity_lowres_mods.RDS"))
wave_2_speeches_spectrum_lowres_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_spectrum_lowres_mods.RDS"))
```



```{r}
# PREDICTIONS IN SPACE FROM -1 TO 7
mypredict <- function(m, newdata = NULL, ...) {
  UseMethod("mypredict", m)
}
mypredict.lmerModLmerTest <- function(m, newdata = NULL, ...) {
  if(is.null(newdata)) newdata <- model.frame(m)
  predict(m, newdata = newdata, ...)
}
mypredict.clmm <- function(m, newdata = NULL, ...) {
  if(is.null(newdata)) newdata <- model.frame(m)
  left_join(newdata, as.data.frame(ref_grid(m, mode = "mean.class")))$mean.class-2
}
mypredict.glmerMod <- function(m, newdata = NULL, ...) {
  if(is.null(newdata)) newdata <- model.frame(m)
  predict(m, newdata = newdata, type="response")*8-1
}
```

```{r}
predict_by_rating <- function(df, mod){
  df <- df %>% filter(!is.na(rating), Ethnicity != "CONSENT_REVOKED")
  y <- df$rating
  yhat <- mypredict(mod)
  df %>% mutate(y=y, yhat=yhat)
}
```

```{r}
wave_1_yhat_dfs <- list(
  pilot_1_lyrics = predict_by_rating(wave_1_dfs$pilot_1_lyrics, wave_1_mods$pilot_1_lyrics), 
  wave_1_lyrics = predict_by_rating(wave_1_dfs$wave_1_lyrics, wave_1_mods$wave_1_lyrics))
```

```{r}
#plot_observed_predicted <- function(df_list, column){
df_list <- wave_1_yhat_dfs
column <- "value"

  lapply(seq_along(df_list), function(df, n, i){
    
    y <- df[[i]]$y
    yhat <- df[[i]]$yhat
  
    tss <- sum((y-mean(y))^2)
    rss <- sum((y-yhat)^2)
    r2 <- 1-rss/tss
     
    plot_1 <- df[[i]] |>
      mutate(y = y, yhat = yhat) |>
      ggplot(aes(y,yhat)) +
      geom_point(alpha = .03) +
      geom_abline(intercept = 0, slope = 1, color = "red") +
      labs(title = paste(collapse=" ", c(n[[i]], r2))) +
      theme_minimal()
    
    plot_2 <- plot_1 + facet_wrap(~.data[[column]])
    
    plot_grid(plot_1, plot_2)
    
  }, n = names(df_list), df = df_list)
```

```{r}
# COMPUTE R^2 AND BOXPLOTS OF PREDICTION BY OBSERVED RATING
predict_by_rating <- function(df, mods){
  
  df <- df %>% filter(!is.na(rating), Ethnicity != "CONSENT_REVOKED")
  
  lmer <- mods$lmer
  clmm <- mods$clmm
  glmer<- mods$glmer
  
  yhat_dfs <- lapply(
    c("lmer", "clmm", "glmer"), function(n) {
      y <- df$rating
      yhat <- mypredict(get(n)) # get predictions from fitted model using custom function
      
      df %>% mutate(y=y, yhat=yhat)
    
  })
  
  names(yhat_dfs) <- c("lmer", "clmm", "glmer")
  return(yhat_dfs)
}
```

```{r}
pilot_2_lyrics_yhat_dfs <- predict_by_rating(wave_2_dfs$pilot_2_lyrics, wave_2_lyrics_mods$pilot_2_lyrics)
saveRDS(pilot_2_lyrics_yhat_dfs, here("_data", "_intermediary_data", "models", "pilot_2_lyrics_yhat_dfs.RDS"))

pilot_2_speeches1_yhat_dfs <- predict_by_rating(wave_2_dfs$pilot_2_speeches1, wave_2_speeches_ethnicity_mods$pilot_2_speeches1)
saveRDS(pilot_2_speeches1_yhat_dfs, here("_data", "_intermediary_data", "models", "pilot_2_speeches1_yhat_dfs.RDS"))

pilot_2_speeches2_yhat_dfs <- predict_by_rating(wave_2_dfs$pilot_2_speeches2, wave_2_speeches_spectrum_mods$pilot_2_speeches_2)
saveRDS(pilot_2_speeches2_yhat_dfs, here("_data", "_intermediary_data", "models", "pilot_2_speeches2_yhat_dfs.RDS"))
```

```{r}
# wave_2_lyrics_yhat_dfs <- predict_by_rating(wave_2_dfs$wave_2_lyrics, wave_2_lyrics_mods$wave_2_lyrics)
# saveRDS(wave_2_lyrics_yhat_dfs, here("_data", "_intermediary_data", "models", "wave_2_lyrics_yhat_dfs.RDS"))

wave_2_lyrics_yhat_dfs <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_lyrics_yhat_dfs.RDS"))

# wave_2_speeches_ethnicity_yhat_dfs <- predict_by_rating(wave_2_dfs$wave_2_speeches, wave_2_speeches_ethnicity_mods$wave_2_speeches)
# saveRDS(wave_2_speeches_ethnicity_yhat_dfs, here("_data", "_intermediary_data", "models", "wave_2_speeches_ethnicity_yhat_dfs.RDS"))

wave_2_speeches_ethnicity_yhat_dfs <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_ethnicity_yhat_dfs.RDS"))

# wave_2_speeches_spectrum_yhat_dfs <- predict_by_rating(wave_2_dfs$wave_2_speeches, wave_2_speeches_spectrum_mods$wave_2_speeches)
# saveRDS(wave_2_speeches_spectrum_yhat_dfs, here("_data", "_intermediary_data", "models", "wave_2_speeches_spectrum_yhat_dfs.RDS"))

wave_2_speeches_spectrum_yhat_dfs <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_spectrum_yhat_dfs.RDS"))
```

```{r}
plot_observed_predicted <- function(df_list, column){

  lapply(seq_along(df_list), function(df, n, i){
    
    y <- df[[i]]$y
    yhat <- df[[i]]$yhat
  
    tss <- sum((y-mean(y))^2)
    rss <- sum((y-yhat)^2)
    r2 <- 1-rss/tss
     
    plot_1 <- df[[i]] |>
      mutate(y = y, yhat = yhat) |>
      ggplot(aes(as.factor(y),yhat)) +
        geom_boxplot() +
        geom_abline(intercept = -2, slope = 1, color = "red") +
        scale_y_continuous(limits = c(-3, 10), n.breaks = (9))+
        labs(title = paste(collapse=" ", c(n[[i]], r2))) +
        theme_minimal()
    
    plot_2 <- plot_1 + facet_wrap(~.data[[column]])
    
    plot_grid(plot_1, plot_2)
    
  }, n = names(df_list), df = df_list)
}
```

```{r}
plot_observed_predicted(pilot_2_lyrics_yhat_dfs, "value")
plot_observed_predicted(pilot_2_speeches1_yhat_dfs, "value")
plot_observed_predicted(pilot_2_speeches2_yhat_dfs, "value")
```


```{r}
plot_observed_predicted(wave_2_lyrics_yhat_dfs, "value")
plot_observed_predicted(wave_2_speeches_ethnicity_yhat_dfs, "value")
plot_observed_predicted(wave_2_speeches_spectrum_yhat_dfs, "value")
```

```{r}
df <- wave_2_dfs$wave_2_lyrics
mod <- wave_2_lyrics_lowres_mods$wave_2_lyrics$glmer

df <- mod@frame
y <- df$rating
yhat <- predict(mod, type="response")

    tss <- sum((y-mean(y))^2)
    rss <- sum((y-yhat)^2)
    r2 <- 1-rss/tss

df %>%
      mutate(y = rating, yhat = yhat) |>
      ggplot(aes(as.factor(y),yhat)) +
        geom_boxplot() +
        geom_abline(intercept = -1, slope = 1, color = "red") +
        labs(title = paste(collapse=" ", c("glmer", r2))) +
        scale_y_continuous(limits = c(-.5, 1.5))+
        theme_minimal()
```

```{r}
mod <- wave_2_speeches_ethnicity_lowres_mods$wave_2_speeches$glmer

df <- mod@frame
y <- df$rating
yhat <- predict(mod, type="response")

    tss <- sum((y-mean(y))^2)
    rss <- sum((y-yhat)^2)
    r2 <- 1-rss/tss

df %>%
      mutate(y = rating, yhat = yhat) |>
      ggplot(aes(as.factor(y),yhat)) +
        geom_boxplot() +
        geom_abline(intercept = -1, slope = 1, color = "red") +
        labs(title = paste(collapse=" ", c("glmer", r2))) +
        scale_y_continuous(limits = c(-.5, 1.5))+
        theme_minimal()

mod <- wave_2_speeches_spectrum_lowres_mods$wave_2_speeches$glmer

df <- mod@frame
y <- df$rating
yhat <- predict(mod, type="response")

    tss <- sum((y-mean(y))^2)
    rss <- sum((y-yhat)^2)
    r2 <- 1-rss/tss

df %>%
      mutate(y = rating, yhat = yhat) |>
      ggplot(aes(as.factor(y),yhat)) +
        geom_boxplot() +
        geom_abline(intercept = -1, slope = 1, color = "red") +
        labs(title = paste(collapse=" ", c("glmer", r2))) +
        scale_y_continuous(limits = c(-.5, 1.5))+
        theme_minimal()
```

```{r}
mod <- wave_2_lyrics_lowres_mods$wave_2_lyrics$clmm

df <- model.frame(mod)
df <- df %>% mutate(y = case_when(
  rating == "(-2,0]" ~ 1, 
  rating == "(0,6]" ~ 2, 
  rating == "(6,7]" ~ 3
))
y <- df$y

yhat <- left_join(df, as.data.frame(ref_grid(mod, mode = "mean.class")))$mean.class

    tss <- sum((y-mean(y))^2)
    rss <- sum((y-yhat)^2)
    r2 <- 1-rss/tss

df %>%
      mutate(yhat = yhat) |>
      ggplot(aes(as.factor(y),yhat)) +
        geom_boxplot() +
        geom_abline(intercept = 0, slope = 1, color = "red") +
        labs(title = paste(collapse=" ", c("clmm", r2))) +
        scale_y_continuous(limits = c(-.5, 3.5))+
        theme_minimal()
```

```{r}
mod <- wave_2_speeches_ethnicity_lowres_mods$wave_2_speeches$clmm

df <- model.frame(mod)
df <- df %>% mutate(y = case_when(
  rating == "(-2,0]" ~ 1, 
  rating == "(0,6]" ~ 2, 
  rating == "(6,7]" ~ 3
))
y <- df$y

yhat <- left_join(df, as.data.frame(ref_grid(mod, mode = "mean.class")))$mean.class

    tss <- sum((y-mean(y))^2)
    rss <- sum((y-yhat)^2)
    r2 <- 1-rss/tss

df %>%
      mutate(yhat = yhat) |>
      ggplot(aes(as.factor(y),yhat)) +
        geom_boxplot() +
        geom_abline(intercept = 0, slope = 1, color = "red") +
        labs(title = paste(collapse=" ", c("clmm", r2))) +
        scale_y_continuous(limits = c(-.5, 3.5))+
        theme_minimal()
```

```{r}
mod <- wave_2_speeches_spectrum_lowres_mods$wave_2_speeches$clmm

df <- model.frame(mod)
df <- df %>% mutate(y = case_when(
  rating == "(-2,0]" ~ 1, 
  rating == "(0,6]" ~ 2, 
  rating == "(6,7]" ~ 3
))
y <- df$y

yhat <- left_join(df, as.data.frame(ref_grid(mod, mode = "mean.class")))$mean.class

    tss <- sum((y-mean(y))^2)
    rss <- sum((y-yhat)^2)
    r2 <- 1-rss/tss

df %>%
      mutate(yhat = yhat) |>
      ggplot(aes(as.factor(y),yhat)) +
        geom_boxplot() +
        geom_abline(intercept = 0, slope = 1, color = "red") +
        labs(title = paste(collapse=" ", c("clmm", r2))) +
        scale_y_continuous(limits = c(-.5, 3.5))+
        theme_minimal()
```

