---
title: "R Notebook"
---

```{r}
library("here")         # file logistics
library("lme4")         # mixed effects modelling
library("tidyverse")    # code logistics
library("broom.mixed")  # model outputs as data frames
library("specr")        # specification curve logistics
library("emmeans")      # estimated marginal means
#library("parallel")     # parallel processing
# 
# num_cores  <- parallel::detectCores()
# cluster  <- parallel::makeCluster(num_cores-1)

# TO "CENTER" CATEGORICAL PREDICTORS, set the coding to contr.sum (deviations from the average)
options(scipen = 999, contrasts = c("contr.sum", "contr.poly"))

# read in data
wave_2_dfs <- readRDS(here("_data", "_intermediary_data", "wave_2_dfs.RDS"))
```

```{r}
extract_specs <- function(variable, specs){
  
  # remove constants and uninformative variables
  spec_plot <- specs$formula
  spec_plot <- str_replace_all(spec_plot, paste0("rating ~ ", variable, " \\+ "), "")
  spec_plot <- str_replace_all(spec_plot, " \\+ \\(1\\|item_ID\\) \\+ \\(1\\|participant_ID\\)", "")
  spec_plot <- str_replace_all(spec_plot, "1 \\+ ", "")
  
  # create set of unique terms, and remove blank spaces
  t <- str_split_fixed(spec_plot, "\\+ ", n=12) %>% as.data.frame()
  cols <- as.vector(as.matrix(t)) %>% unique()
  cols <- str_replace_all(cols, " ", "")
  
  # create results dataframe, with a colnames for each term
  results_df <- data.frame(matrix(ncol = length(cols), nrow = nrow(t)))
  colnames(results_df) <- cols
  
  # create list of specifications
  s <- str_split(spec_plot, " \\+ ")
  
  # for each spec in  list of specs  
  for(i in 1:length(s)){
    # for each unique term in cols
    for(j in 1:length(cols)){
      # if unique term is in spec
      if(cols[[j]] %in% s[[i]]){
        # fill cell with character
        results_df[i, cols[[j]]] <- "|"}
    }
  }
  # df with colnames for each unique term and character in cell if in spec
  index <- length(results_df)
  results_df <- results_df[, -index]
  return(results_df)
}
```

```{r}
spec_out <- function(df, x, controls, formula_addition){
  
  # extract setups without and with interaction term:
  specs <- setup(data = df, y = c("rating"), x = x, 
                 model = c("lmer"),
                 controls = controls, 
                 fun1 = function(x) broom.mixed::tidy(x,conf.int = TRUE),
                 add_to_formula = "value + (1|item_ID) + (1|participant_ID)",
                 simplify = FALSE)
  
  specs1 <- specs$specs %>% as.data.frame()
  
  specs <- setup(data = df,
                 y = c("rating"), x = x,
                 model = c("lmer"),
                 controls = controls,
                 fun1 = function(x) broom.mixed::tidy(x,conf.int = TRUE),
                 add_to_formula = paste0(formula_addition, " + ", "value + (1|item_ID) + (1|participant_ID)"),
                 simplify = FALSE)
  
  specs2 <- specs$specs %>% as.data.frame()
  
  # merge and format specs object
  specs <- bind_rows(specs1, specs2)
  specs_df <- extract_specs(x, specs) %>% mutate(model_num = seq(1:nrow(specs)))
  specs <- specs %>% mutate(model_num = seq(1:nrow(specs))) %>% select(-model, -subsets, -model_function)
  specs <- merge(specs, specs_df, by = "model_num")
  
  return(specs)
}
```

```{r}
# make sets of specs
speeches_ethnicity_specs <- spec_out(
  df=wave_2_dfs$wave_2_speeches, 
  x="Ethnicity", 
  controls=c("Sex", "Age", "w", "f", "c", "year", "spectrum", "party"), 
  formula_addition="Ethnicity*party")

speeches_spectrum_specs <- spec_out(
  df=wave_2_dfs$wave_2_speeches, 
  x="spectrum", 
  controls=c("Sex", "Age", "w", "f", "c", "year", "Ethnicity", "party"), 
  formula_addition="spectrum*party")

lyrics_ethnicity_specs <- spec_out(
  df = wave_2_dfs$wave_2_lyrics, 
  x="Ethnicity", 
  controls = c("Sex", "Age", "writer_is_speaker", "familiar", "c", 
               "lyrics_topic", "popular", "genre", "year"), 
  formula_addition="Ethnicity*genre")
```

```{r}
spec_out <- function(df, x, controls){
  
  # extract setups without and with interaction term:
  specs <- setup(data = df, y = c("rating"), x = x, 
                 model = c("lmer"),
                 controls = controls, 
                 fun1 = function(x) broom.mixed::tidy(x,conf.int = TRUE),
                 add_to_formula = "value + (1|item_ID) + (1|participant_ID)",
                 simplify = FALSE)
  
  specs <- specs$specs %>% as.data.frame()
  
  
  # merge and format specs object
  specs_df <- extract_specs(x, specs) %>% mutate(model_num = seq(1:nrow(specs)))
  specs <- specs %>% mutate(model_num = seq(1:nrow(specs))) %>% select(-model, -subsets, -model_function)
  specs <- merge(specs, specs_df, by = "model_num")
  
  return(specs)
}
```

```{r}
lyrics_ethnicity_specs <- spec_out(
  df = wave_2_dfs$wave_2_lyrics, 
  x="Ethnicity", 
  controls = c("Sex", "Age", "writer_is_speaker", "familiar", "c", 
               "lyrics_topic", "popular", "genre", "year"))
```


```{r}
# run specification curves
run_spec_curve <- function(specs, df){

  
  # extract formulae
  formulae <- specs$formula%>%as.list()
  
  # time
  start <- Sys.time()
  # run all model formulae
  dfs <- lapply(formulae, function(formula){
  
    mod <- lmer(as.formula(formula), data = df)
    emm <- emmeans(mod, ~Ethnicity) 
    emm <- emm %>% as.data.frame()
    emm$AIC <- AIC(mod)
    return(emm)
  })
  print(Sys.time() - start)
  
  # add model number to each output
  for(i in 1:length(dfs)){
    dfs[[i]]$model_num <- i
  }
  
  # bind into single df
  spec_curve_df <- bind_rows(dfs)
  spec_curve_df <- merge(spec_curve_df, specs, by = "model_num")
  
  return(spec_curve_df)
}
```

# these only run if run one at a time

```{r}
emm_options(rg.limit = 15000000)

wave_2_lyrics_ethnicity_curve_df <- run_spec_curve(lyrics_ethnicity_specs%>%filter(model_num<500), df = wave_2_dfs$wave_2_lyrics)

saveRDS(wave_2_lyrics_ethnicity_curve_df, file = here("_data", "_intermediary_data", "spec_curves", "wave_2_lyrics_ethnicity_curve_df.RDS"))
```

```{r}
specs <- lyrics_ethnicity_specs%>%filter(model_num>=500)
formulae <- specs$formula%>%as.list()
names(formulae) <- specs$model_num
df <- wave_2_dfs$wave_2_lyrics

  
  # run all model formulae
  mods <- lapply(formulae, function(formula){
    lmer(as.formula(formula), data = df)
  
  })
  
  emm_options(rg.limit = 15000000)
  emms <- lapply(mods, function(mod){
    emm <- emmeans(mod, ~Ethnicity)
    
  })
  
  emm_dfs <- lapply(emms, function(emm){
    emm <- emm %>% as.data.frame()
  })
  
  spec_curve_df <- bind_rows(emm_dfs, .id = "model_num")

  AICs <- lapply(mods, function(mod){
    AIC <- AIC(mod) 
  }) 
  
  AIC_df <- AICs %>% as.data.frame() %>% t() %>% as.data.frame() %>%
    rownames_to_column(var = "model_num") %>%
    mutate(model_num = str_remove(model_num, "X")) %>%
    rename(AIC = V1)
  
  spec_curve_df <- merge(spec_curve_df, AIC_df, by = "model_num") %>%
    mutate(model_num = as.numeric(model_num))
  
  spec_curve_df <- merge(spec_curve_df, specs, by = "model_num")
  
  wave_2_lyrics_ethnicity_curve_df <- bind_rows(wave_2_lyrics_ethnicity_curve_df, spec_curve_df)
  
  
saveRDS(wave_2_lyrics_ethnicity_curve_df, file = here("_data", "_intermediary_data", "spec_curves", "wave_2_lyrics_ethnicity_curve_df_500.RDS"))
```


```{r}
emm_options(rg.limit = 15000000)

wave_2_lyrics_ethnicity_curve_df_500 <- run_spec_curve(lyrics_ethnicity_specs%>%filter(model_num>=500), df = wave_2_dfs$wave_2_lyrics)

saveRDS(wave_2_lyrics_ethnicity_curve_df_500, file = here("_data", "_intermediary_data", "spec_curves", "wave_2_lyrics_ethnicity_curve_df_500.RDS"))
```

```{r}
wave_2_speeches_ethnicity_curve_df <- run_spec_curve(speeches_ethnicity_specs, df = wave_2_dfs$wave_2_speeches)

saveRDS(wave_2_speeches_ethnicity_curve_df, file = here("_data", "_intermediary_data", "spec_curves", "wave_2_speeches_ethnicity_curve_df.RDS"))
```

```{r}
# run specification curves
df <- wave_2_dfs$wave_2_speeches
specs <- speeches_spectrum_specs

# extract formulae
formulae <- specs$formula%>%as.list()

# time
start <- Sys.time()
# run all model formulae
dfs <- mclapply(formulae, function(formula){

  mod <- lmer(as.formula(formula), data = df)
  emm <- emmeans(mod, ~spectrum)
  emm <- emm %>% as.data.frame()
  emm$AIC <- AIC(mod)
  return(emm)
})
print(Sys.time() - start)

# add model number to each output
for(i in 1:length(dfs)){
  dfs[[i]]$model_num <- i
}

# bind into single df
spec_curve_df <- bind_rows(dfs)
# merge df with specifications object
spec_curve_df <- merge(spec_curve_df, specs, by = "model_num")


# save object
saveRDS(spec_curve_df, file = here("_data", "_intermediary_data", "spec_curves", "wave_2_speeches_spectrum_curve_df.RDS"))
#spec_curve_df <- readRDS(here("_data", "_intermediary_data", "spec_curves", "wave_2_speeches_ethnicity_curve_df.RDS"))
```


# lyrics spec 1

```{r}
df <- wave_2_dfs$wave_2_lyrics

specs <- lyrics_ethnicity_specs
  
formulae <- specs$formula%>%as.list()
#formula <- formulae[[50]]

emm_options(lmerTest.limit = 500000)
# time
start <- Sys.time()
dfs <- lapply(formulae, function(formula){

  mod <- lmer(as.formula(formula), data = df)
  emm <- emmeans(mod, ~Ethnicity, rg.limit = 500000)
  emm <- emm %>% as.data.frame()
  emm$AIC <- AIC(mod)
  return(emm)
})
print(Sys.time() - start)

for(i in 1:length(dfs)){
  dfs[[i]]$model_num <- i
}

spec_curve_df <- bind_rows(dfs)
saveRDS(spec_curve_df, file = here("_data", "_intermediary_data", "spec_curves", "wave_2_lyrics_ethnicity_curve_df.RDS"))

# spec_curve_df <- readRDS(here("_data", "_intermediary_data", "spec_curves", "wave_2_lyrics_ethnicity_curve_df.RDS.RDS"))
```

```{r}
df <- wave_2_dfs$wave_2_lyrics

specs <- lyrics_ethnicity_specs
  
formulae <- specs$formula%>%as.list()

mods <- lapply(formulae, function(formula){
  tryCatch(expr= {
    lmer(as.formula(formula), data = df) 
  }, error = function(e){
    return(NA)
  })
})
```

