---
title: "rater number estimation"
---


```{r}
library('here')       # file logistics
library("tidyverse")  # code logistics
library("patchwork")  # merge plots
library("gt")         # markdown
library("ggtext")     # text plots
```

```{r}
# read in data
file_path <- here("_data", "_intermediary_data", "bootstrapped_ICC")

# summary dfs
pilot_2_likert_summary_dfs   <- readRDS(here(file_path, "pilot_2_likert_summary_dfs.RDS"))

# text type sampled by row
pilot_2_lyrics_by_row_dfs    <- readRDS(here(file_path, "pilot_2_lyrics_by_row_dfs.RDS"))
pilot_2_speeches1_by_row_dfs <- readRDS(here(file_path, "pilot_2_speeches1_by_row_dfs.RDS"))
pilot_2_speeches2_by_row_dfs <- readRDS(here(file_path, "pilot_2_speeches2_by_row_dfs.RDS"))

rm(file_path)
```

```{r}
# apa formatting
theme_apa <- function(base_size = 12, base_family = "sans") {
  theme_minimal(base_size = base_size, base_family = base_family) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black"),
      axis.ticks = element_line(color = "black"),
      axis.title = element_text(size = base_size, face = "plain"),
      axis.text = element_text(size = base_size * 0.9),
      legend.position = "none",
      legend.title = element_text(face = "plain"))}
```

```{r}
# plot ICC2k and 95% CI by value
plot_summary_by_metric <- function(df, metric, metric_lower, metric_upper, option) {
  
  subsets <- as.list(df$subset%>%unique())
  
  lapply(subsets, function(sub){
    df %>%
      filter(subset == sub) %>%
      ggplot(aes(y=value, x={{metric}}, color = value)) +
      geom_point() +
      geom_errorbar(aes(xmin = {{metric_lower}}, xmax = {{metric_upper}})) +
      geom_vline(xintercept = 0.75, color = "red", size = .4, linetype = "dashed" )+
      xlim(-.5, 1) +
      scale_color_viridis_d(option = option) +
      theme(legend.position="none",
            plot.title = element_text(size = 10, hjust = 0.0)) +
      labs(x = "ICC[2,k]",y = "Value") +
      ggtitle(label = sub) +
      theme_apa()
    })}
```

```{r}
# density plot of bootstrapping procedure
plot_raters <- function(df, metric, name, option){
  df %>%
    ggplot(aes(x = {{metric}}, color = as.factor(n))) +
    geom_line(stat = "density", alpha = .5, size = .75) +
    xlim(0, 1) + ylim(0,10) +
    scale_color_viridis_d(option = option, direction = -1) +
    labs(color = "Rater n\n") +  
    ylab("Probability Density") +
    xlab({{name}}) +
    theme_apa() +
    theme(legend.position = "right")
}
```

```{r warning=FALSE}
p1 <- plot_raters(
  pilot_2_lyrics_by_row_dfs[[1]] %>% filter(n <= 25), 
  metric = r, "Pearson's r", option = "plasma") + 
  geom_vline(xintercept = 0.9, color = "red", size = .4, linetype = "dashed") 

p2 <- plot_raters(
  pilot_2_lyrics_by_row_dfs[[1]] %>% filter(n <= 25), 
  metric = ICC2k, "ICC(2,k)", option = "plasma") +
  geom_vline(xintercept = 0.75, color = "red", size = .4, linetype = "dashed") 

(p1 /p2) +
    plot_annotation(
    title = "**Figure 2**",
    subtitle = "*Reliability by Rater n: Lyrics Pilot*", 
    caption = "*Note.* Probability Density for Pearson's r and ICC(2,k).", 
    tag_levels = 'A') +
  
  plot_layout(guides = "collect") &
  
  theme(legend.position = "right",
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

```

```{r warning=FALSE}
p1 <- plot_raters(
  pilot_2_speeches1_by_row_dfs[[1]] %>% filter(n >= 25), 
  metric = r, "Pearson's r", option = "viridis") + 
  geom_vline(xintercept = 0.9, color = "red", size = .4, linetype = "dashed")

p2 <- plot_raters(
  pilot_2_speeches1_by_row_dfs[[1]] %>% filter(n >= 25), 
  metric = ICC2k, "ICC(2,k)", option = "viridis") +
  geom_vline(xintercept = 0.75, color = "red", size = .4, linetype = "dashed")

(p1 /p2) +
    plot_annotation(
    title = "**Figure 3**",
    subtitle = "*Reliability by Rater n: Speeches 1 Pilot*", 
    caption = "*Note.* Probability Density for Pearson's r and ICC(2,k).", 
    tag_levels = 'A') +
  
  plot_layout(guides = "collect") &
  
  theme(legend.position = "right",
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))
```

```{r warning=FALSE}
p1 <- plot_raters(
  pilot_2_speeches2_by_row_dfs[[1]] %>% filter(n >= 25), 
  metric = r, "Pearson's r", option = "viridis") + 
  geom_vline(xintercept = 0.9, color = "red", size = .4, linetype = "dashed")

p2 <- plot_raters(
  pilot_2_speeches2_by_row_dfs[[1]] %>% filter(n >= 25), 
  metric = ICC2k, "ICC(2,k)", option = "viridis") +
  geom_vline(xintercept = 0.75, color = "red", size = .4, linetype = "dashed")

(p1 /p2) +
    plot_annotation(
    title = "**Figure 4**",
    subtitle = "*Reliability by Rater n: Speeches 2 Pilot*", 
    caption = "*Note.* Probability Density for Pearson's r and ICC(2,k).", 
    tag_levels = 'A') +
  
  plot_layout(guides = "collect") &
  
  theme(legend.position = "right",
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))
```


```{r}
# compute plots
pilot_2_lyrics_agreement_plots <- plot_summary_by_metric(
  pilot_2_likert_summary_dfs[[1]], 
  ICC2k, ICC2k_lower, ICC2k_upper, 
  option = "plasma")

pilot_2_speeches1_agreement_plots <- plot_summary_by_metric(
  pilot_2_likert_summary_dfs[[2]], 
  ICC2k, ICC2k_lower, ICC2k_upper, 
  option="viridis")

pilot_2_speeches2_agreement_plots <- plot_summary_by_metric(
  pilot_2_likert_summary_dfs[[3]], 
  ICC2k, ICC2k_lower, ICC2k_upper, 
  option = "viridis")
```

```{r}
p1 <- pilot_2_lyrics_agreement_plots[[1]] 

p1 + 
  ggtitle("**Figure 5**", subtitle = "*ICC(2,k) estimates by Schwartz value*") + 
  labs(caption = 
       "*Note.* Error bars are 95% confidence intervals. 
       'Self' indicates reliability for the value 'self direction'.") +
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))
```

```{r}
p1_1 <- pilot_2_lyrics_agreement_plots[[2]]
p1_2 <- pilot_2_lyrics_agreement_plots[[3]]
p1_3 <- pilot_2_lyrics_agreement_plots[[4]]
p1_4 <- pilot_2_lyrics_agreement_plots[[5]]


(p1_1 | p1_2) / (p1_3 | p1_4) +
  
  plot_annotation(
    title = "**Figure 6**",
    subtitle = "*ICC(2,k) by Schwartz value, by Ethnicity: Lyrics Pilot*", 
    caption = 
         "*Note.* Error bars are 95% confidence intervals. 
         'Self' indicates reliability for the value 'self direction'.") &
  
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))
```



```{r}
p2 <- pilot_2_speeches1_agreement_plots[[1]]
p3 <- pilot_2_speeches2_agreement_plots[[1]]

(p2/p3) + 
  plot_annotation(
    title = "**Figure 7**",
    subtitle = "*ICC(2,k) by Schwartz value, by Ethnicity: Speeches Pilots 1 and 2*", 
    caption = 
    "*Note.* Error bars are 95% confidence intervals. 
         'Self' indicates reliability for the value 'self direction'.", 
    tag_levels = '1') &
  
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))
```

```{r}
p1_1 <- pilot_2_speeches1_agreement_plots[[2]]
p1_2 <- pilot_2_speeches1_agreement_plots[[3]]
p1_3 <- pilot_2_speeches1_agreement_plots[[4]]
p1_4 <- pilot_2_speeches1_agreement_plots[[5]]

(p1_1 | p1_2) / (p1_3 | p1_4) +
  
  plot_annotation(
    title = "**Figure 8**",
    subtitle = "*ICC(2,k) by Schwartz value, by Ethnicity: Speeches 1 Pilot*", 
    caption = 
         "*Note.* Error bars are 95% confidence intervals. 
         'Self' indicates reliability for the value 'self direction'.") &
  
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))
```

```{r}
p1_1 <- pilot_2_speeches2_agreement_plots[[2]]
p1_2 <- pilot_2_speeches2_agreement_plots[[3]]
p1_3 <- pilot_2_speeches2_agreement_plots[[4]]
p1_4 <- patchwork::plot_spacer()

((p1_1 / p1_2) | (p1_3 / p1_4)) +
  plot_annotation(
    title = "**Figure 9**",
    subtitle = "*ICC(2,k) by Schwartz value, by Political Leaning: Speeches 2 Pilot*", 
    caption = 
         "*Note.* Error bars are 95% confidence intervals. 
         'Self' indicates reliability for the value 'self direction'.") &
  
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))
```







