---
title: "R Notebook"
---

```{r}
library("here")         # file logistics
library("lme4")         # mixed effects metric
library("lmerTest")     # p values
library("tidyverse")    # code logistics
library("broom.mixed")  # model outputs as data frames
library("emmeans")      # estimated marginal means
library("patchwork")    # merge plots
library("report")       # apa reporting
library("gt")           # latex tables
library("effectsize")   # partial eta sq calculations

# TO "CENTER" CATEGORICAL PREDICTORS, set the coding to contr.sum (deviations from the average)
options(scipen = 999, contrasts = c("contr.sum", "contr.poly"))
path <- here("_data", "_intermediary_data", "models")
```


```{r}
# read in data
wave_2_dfs <- readRDS(here("_data", "_intermediary_data", "wave_2_dfs.RDS"))

df <- bind_rows(wave_2_dfs$wave_2_lyrics |> 
                  mutate(text = "Lyrics") |>
                  select(participant_ID, item_ID, value, rating, text), 
                wave_2_dfs$wave_2_speeches |> 
                  mutate(text = "Speeches") |>
                  select(participant_ID, item_ID, value, rating, text))

df <- df |> mutate(value = as.factor(value), text = as.factor(text))
```

# lyrics: model selection

```{r}
# lyrics_mod_1 <- lmer(rating ~ value + Ethnicity * genre + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_lyrics, REML = F)
#   
# lyrics_mod_2 <- lmer(rating ~ value * Ethnicity * genre + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_lyrics, REML = F)
# 
# anova <- anova(lyrics_mod_1, lyrics_mod_2)
# anova

#saveRDS(anova, here(path, "wave_2_lyrics_mods_anova.RDS"))

anova <- readRDS(here(path, "wave_2_lyrics_mods_anova.RDS"))
anova
```

## two models in multi-verse

estimate and report on:

lyrics1: pre-registered model
lyrics2: best fitting model

```{r}
# lyrics_mod_1 <- lmer(rating ~ value + Ethnicity * genre + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_lyrics, REML = T)
# saveRDS(lyrics_mod_1, here(path, "wave_2_lyrics_mod_1.RDS"))

lyrics_mod_1 <- readRDS(here(path, "wave_2_lyrics_mod_1.RDS"))

# anova <- anova(lyrics_mod_1, type = "III")
# saveRDS(anova, here(path, "wave_2_lyrics_mod_1_anova.RDS"))
# 
anova <- readRDS(here(path, "wave_2_lyrics_mod_1_anova.RDS"))
anova

# eta_df <- eta_squared(lyrics_mod_1, partial = TRUE, ci = 0.95) 
# eta_df <- eta_df |>
#   select(Parameter, Eta2_partial, CI_low, CI_high) |>
#   rename(Effect = Parameter)
# saveRDS(eta_df, here(path, "wave_2_lyrics1_eta_df.RDS"))
eta_df <- readRDS(here(path, "wave_2_lyrics1_eta_df.RDS"))
eta_df
```

```{r}
#lyrics_mod_2 <- lmer(rating ~ value * Ethnicity * genre + (1|item_ID) + (1 | participant_ID),
#  data = wave_2_dfs$wave_2_lyrics, REML = T)
# saveRDS(lyrics_mod_2, here(path, "wave_2_lyrics_mod_2.RDS"))

lyrics_mod_2 <- readRDS(here(path, "wave_2_lyrics_mod_2.RDS"))
# 
# anova <- anova(lyrics_mod_2, type = "III")
# saveRDS(anova, here(path, "wave_2_lyrics_mod_2_anova.RDS"))

anova <- readRDS(here(path, "wave_2_lyrics_mod_2_anova.RDS"))
anova

# estimate effect size
# eta_df <- eta_squared(lyrics_mod_2 , partial = TRUE, ci = 0.95) 
# eta_df <- eta_df |>
#   select(Parameter, Eta2_partial, CI_low, CI_high) |>
#   rename(Effect = Parameter)
# saveRDS(eta_df, here(path, "wave_2_lyrics2_eta_df.RDS"))

eta_df <- readRDS(here(path, "wave_2_lyrics2_eta_df.RDS"))
eta_df
```

# speeches: model selection

```{r}
# # Ethnicity Mods
# speeches1a_mod <- lmer(rating ~ value + Ethnicity * party + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_speeches, REML = F)
# 
# speeches2a_mod <- lmer(rating ~ value * Ethnicity * party + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_speeches, REML = F)
# 
# # Spectrum Mods
# speeches1b_mod <- lmer(rating ~ value + spectrum * party + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_speeches, REML = F)
# 
# speeches2b_mod <- lmer(rating ~ value * spectrum * party + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_speeches, REML = F)
# 
# # Combined Mods
# speeches3_mod <- lmer(rating ~ value * Ethnicity * spectrum + party + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_speeches, REML = F)
# 
# speeches4_mod <- lmer(rating ~ value * Ethnicity * spectrum * party + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_speeches, REML = F)
# 
# speeches_a_mods <- list(
#   speeches1a_mod = speeches1a_mod, 
#   speeches2a_mod = speeches2a_mod,
#   speeches3_mod  = speeches3_mod, 
#   speeches4_mod  = speeches4_mod)
# 
# speeches_b_mods <- list(
#   speeches1b_mod = speeches1b_mod, 
#   speeches2b_mod = speeches2b_mod, 
#   speeches3_mod  = speeches3_mod, 
#   speeches4_mod  = speeches4_mod) 
# 
# saveRDS(speeches_a_mods, here(path, "speeches_a_mods.RDS"))
# saveRDS(speeches_b_mods, here(path, "speeches_b_mods.RDS"))
```

```{r}
speeches_a_mods <- readRDS(here(path, "speeches_a_mods.RDS"))
speeches_b_mods <- readRDS(here(path, "speeches_b_mods.RDS"))
```

## report on model selection

### model comparison table

```{r}
# take sequential series of models, 
# extract fit indices, 
# compare each model to previous in series

model_comparison_table <- function(model_list) {
  
  # Ensure named list
  if (is.null(names(model_list))) {
    names(model_list) <- paste0("mod", seq_along(model_list))
  }
  
  n_models <- length(model_list)
  
  # 1. Pseudo R2 (Nakagawa)
  r2_df <- purrr::map_df(model_list, ~ as.data.frame(performance::r2_nakagawa(.x)))
  
  # 2. AIC
  aic_vals <- sapply(model_list, AIC)
  
  # 3. Formulas
  formulas <- purrr::map_chr(model_list, ~ paste(deparse(formula(.x)), collapse = " "))
  
  # 4. Sequential LRT
  lrt_chisq <- numeric(n_models)
  lrt_df    <- numeric(n_models)
  raw_p     <- numeric(n_models)
  
  # first is always NA, as there is nothing to compare it to
  lrt_chisq[1] <- NA
  lrt_df[1]    <- NA
  raw_p[1]     <- NA
  
  for (i in 2:n_models) {
    # anova for previous model and current model
    a <- suppressWarnings(anova(model_list[[i-1]], model_list[[i]]))
    lrt_chisq[i] <- a$Chisq[2]
    lrt_df[i]    <- a$Df[2]
    raw_p[i]     <- a$`Pr(>Chisq)`[2]
  }
  
  # 5. Format p-values
  format_p <- function(p) {
    if (is.na(p)) return(NA_character_)
    if (p < 0.0001) return("< .0001")
    if (p < 0.001)  return("< .001")
    if (p < 0.01)   return(sprintf("= %.3f", p))
    return(sprintf("= %.3f", p))
  }
  
  LRT_p <- vapply(raw_p, format_p, FUN.VALUE = character(1))
  
  # 6. ΔAIC relative to previous model
  delta_prev <- c(NA, diff(aic_vals))
  
  tibble::tibble(
    Model           = names(model_list),
    Specification   = formulas,
    AIC             = aic_vals,
    Delta_AIC_prev  = delta_prev,
    R2_marginal     = r2_df$R2_marginal,
    R2_conditional  = r2_df$R2_conditional,
    LRT_chisq       = lrt_chisq,
    LRT_df          = lrt_df,
    LRT_p           = LRT_p
  )
}

```


```{r}
speech_tbls <- bind_rows(
  model_comparison_table(speeches_a_mods) |> mutate(Group = "Ethnicity Models"), 
  model_comparison_table(speeches_b_mods) |> mutate(Group = "Spectrum Models")) |>
  
  mutate(Model = gsub("_mod", "", Model))

speech_tbl <- speech_tbls |>select(-Specification) |>

  gt(groupname_col = "Group") |>
  
  cols_label(
    Model           = "Model",
    AIC             = "AIC",
    Delta_AIC_prev  = html("$\\Delta$AIC"),
    R2_marginal     = html("$R^2_m$"),
    R2_conditional  = html("$R^2_c$"),
    LRT_chisq       = html("$\\chi^2$"),
    LRT_df          = html("df"),
    LRT_p           = html("p")
  ) |>
  
  fmt_number(
    columns = c(AIC, Delta_AIC_prev, R2_marginal, R2_conditional, LRT_chisq),
    decimals = 3) |>
  
  tab_header(title = "Model Comparisons: Ethnicity, and Political Spectrum")

speech_tbl
```

### model specification table

```{r}
extract_spec_pretty <- function(model) {
  
  # 1. Get raw formula string without R's line breaks
  f_raw <- paste(deparse(model@call$formula, width.cutoff = 500), collapse = " ")
  
  # 2. Normalize spacing
  f_raw <- gsub("\\s+", " ", f_raw)
  
  # 3. Split into fixed and random parts
  #    This finds the first "(" that starts a random-effect term.
  split_pos <- regexpr("\\(1 \\|", f_raw)
  
  if (split_pos == -1) {
    # No random effects
    fixed <- f_raw
    random <- ""
  } else {
    fixed  <- trimws(substr(f_raw, 1, split_pos - 1))
    random <- trimws(substr(f_raw, split_pos, nchar(f_raw)))
  }
  
  # 4. Clean random effects:
  #    remove internal newlines, enforce single-line spacing
  random <- gsub("\\s*\\+\\s*", " + ", random)
  random <- gsub("\\s+", " ", random)
  
  # 5. Rebuild the final pretty spec:
  pretty <- paste0(fixed, "<br>", random)
  
  html(pretty)
}


speeches_a_specs <- tibble(
  Group = "Ethnicity Models",
  Model = names(speeches_a_mods),
  Specification = purrr::map(speeches_a_mods, extract_spec_pretty)
)

speeches_b_specs <- tibble(
  Group = "Political Spectrum Models",
  Model = names(speeches_b_mods),
  Specification = purrr::map(speeches_b_mods, extract_spec_pretty)
)

spec_table <- bind_rows(speeches_a_specs, speeches_b_specs) |> mutate(Model = gsub("_mod", "", Model))

gt_specs <- spec_table |>
  gt(groupname_col = "Group") |>
  cols_width(
    Model ~ px(150),
    Specification ~ px(400) 
  ) |>
  cols_align("left", columns = Specification) |>
  tab_style(
    style = cell_text(weight = "bold", align = "center"),
    locations = cells_row_groups()
  ) |>
  tab_header(
    title = "Models Specifications: Ethnicity, and Political Spectrum"
  )


gt_specs
```

```{r}
gtsave(speech_tbl, here("tables", "main_speech_model_comparisons.tex"))
gtsave(gt_specs,here("tables", "main_speech_model_specifications.tex"))
```

## three models in multi-verse

speeches1a & speeches1b: preregistered models
speeches4: best fitting model

```{r}
speeches1a_mod <- speeches_a_mods[["speeches1a_mod"]]

anova <- anova(speeches1a_mod)
anova

eta_df <- eta_squared(speeches1a_mod, partial = TRUE, ci = 0.95)
eta_df <- eta_df |>
  select(Parameter, Eta2_partial, CI_low, CI_high) |>
  rename(Effect = Parameter)
eta_df
```

```{r}
speeches1b_mod <- speeches_b_mods[["speeches1b_mod"]]

anova <- anova(speeches1b_mod)
anova

eta_df <- eta_squared(speeches1b_mod, partial = TRUE, ci = 0.95)
eta_df <- eta_df |>
  select(Parameter, Eta2_partial, CI_low, CI_high) |>
  rename(Effect = Parameter)
eta_df
```


```{r}
# estimate model

# speeches4_mod <- lmer(rating ~ value * Ethnicity * spectrum * party + (1|item_ID) + (1 | participant_ID), 
#   data = wave_2_dfs$wave_2_speeches, REML = T)
# 
# saveRDS(speeches4_mod, here(path, "wave_2_speeches4_mod.RDS"))

speeches4_mod <- readRDS(here(path, "wave_2_speeches4_mod.RDS"))

# estimate anova
# anova <- anova(speeches4_mod, type = "III")
# saveRDS(anova, here(path, "wave_2_speeches4_mod_anova.RDS"))
anova <- readRDS(here(path, "wave_2_speeches4_mod_anova.RDS"))
anova
# estimate effect size
# eta_df <- eta_squared(speeches4_mod, partial = TRUE, ci = 0.95)
# eta_df <- eta_df |>
#   select(Parameter, Eta2_partial, CI_low, CI_high) |>
#   rename(Effect = Parameter)
# saveRDS(eta_df, here(path, "wave_2_speech4_eta_df.RDS"))

eta_df <- readRDS(here(path, "wave_2_speech4_eta_df.RDS"))
eta_df
```


