---
title: "R Notebook"
---

```{r}
library("here")             # file logistics
library("tidyverse")        # code logistics
library("emmeans")          # estimated marginal means
library("PlackettLuce")     # rank aggregation
library("patchwork")        # merge plots

options(scipen = 999)
```

# estimate canonical rankings using Plackett-Luce modelling

```{r}
pl_dfs <- lapply(wave_2_dfs, function(df){

  ranking_df <- df |>
    
    # pl models can't rank NAs
    filter(!is.na(rating)) |>
    group_by(item_ID, participant_ID) |>
    # pl models can't rank when there's only 1 value ranked
    filter(n() > 1) |>
    mutate(rank = dense_rank(-rating)) |>
    ungroup()
  
})
```


```{r}
lyrics_pl <- pl_dfs[["wave_2_lyrics"]] |>
    
    group_by(item_ID) |>
    
    group_modify(~ {

      # return empty tibble if less than 2 participants for an item
      if (n_distinct(.x$participant_ID) < 2) {
        return(tibble())
      }

      # return empty tibble if less than 2 ranks for an item
      if (n_distinct(.x$rank) < 2) {
        return(tibble())
      }

      # return empty tibble if there is an error
      fit <- tryCatch({

        R <- rankings(
          item = "value",
          rank = "rank",
          id   = "participant_ID",
          data = .x
        )

        # run pl model on rankings for a single item
        PlackettLuce(R)

      }, error = function(e) {
        return(NULL)
      })

      if (is.null(fit)) return(tibble())

      vc <- tryCatch(vcov(fit), error = function(e) NULL)
      if (is.null(vc)) return(tibble())

      tibble(
        value = names(coef(fit)),
        worth = as.numeric(coef(fit)),
        se    = sqrt(diag(vc))
      )
    })


saveRDS(lyrics_pl, here("_data", "_intermediary_data", "models", "lyrics_pl_df.RDS"))
```

```{r}
speeches_pl <- pl_dfs[["wave_2_speeches"]] |>
    
    group_by(item_ID, Ethnicity, spectrum) |>
    
    group_modify(~ {

      # return empty tibble if less than 2 participants for an item
      if (n_distinct(.x$participant_ID) < 2) {
        return(tibble())
      }

      # return empty tibble if less than 2 ranks for an item
      if (n_distinct(.x$rank) < 2) {
        return(tibble())
      }

      # return empty tibble if there is an error
      fit <- tryCatch({

        R <- rankings(
          item = "value",
          rank = "rank",
          id   = "participant_ID",
          data = .x
        )

        # run pl model on rankings for a single item
        PlackettLuce(R)

      }, error = function(e) {
        return(NULL)
      })

      if (is.null(fit)) return(tibble())

      vc <- tryCatch(vcov(fit), error = function(e) NULL)
      if (is.null(vc)) return(tibble())

      tibble(
        value = names(coef(fit)),
        worth = as.numeric(coef(fit)),
        se    = sqrt(diag(vc))
      )
    })


saveRDS(speeches_pl, here("_data", "_intermediary_data", "models", "speeches_pl_df.RDS"))
```
