---
title: "R Notebook"
---

```{r}
library("here")         # file logistics
library("tidyverse")    # code logistics
library("diptest")      # unimodality
library("mclust")
library("DescTools")
library("poLCA")
library("patchwork")    # merge plots
library("gt")           # latex tables

# Schwartz value inventory
values <- c("POWER", "ACHIEVEMENT", "HEDONISM",  
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION",  
            "CONFORMITY", "SECURITY")

options(scipen = 999)
# TO "CENTER" CATEGORICAL PREDICTORS, set the coding to contr.sum (deviations from the average)
options(contrasts = c("contr.sum", "contr.poly"))
```

```{r}
# read in data
path <- here("_data", "_intermediary_data")
wave_2_dfs <- readRDS(here(path, "wave_2_dfs.RDS"))

# center midpoint at 0
midpoint = 3

wave_2_dfs <- lapply(wave_2_dfs, function(df){
  df |> mutate(rating_centered = rating - midpoint)  
})
```


```{r}
summary_dfs <- lapply(wave_2_dfs, function(df){
  
  df |>
    group_by(item_ID, value) |>
    summarise(mean = mean(rating_centered, na.rm=T), sd = sd(rating_centered, na.rm=T)) |>
    ungroup() |>
    mutate(item_ID = as.factor(item_ID))
})
```

```{r}
metrology_plot <- function(summary_df, option){
  summary_df |>
    ggplot(aes(mean, sd, color = value)) +
      geom_point(alpha = 0.05) +
      facet_wrap(~ value, ncol = 2) +
      scale_x_continuous(limits = c(-4, 4)) +
      scale_y_continuous(limits = c(0, 5)) +
      theme_classic() + 
      scale_color_viridis_d(option = option) +
      theme(legend.position = "none")
}  

plots <- list(lyrics = metrology_plot(summary_dfs[[1]], "plasma"), 
              speeches = metrology_plot(summary_dfs[[2]], "D"))

(plots[[1]] | plots[[2]])
```

```{r}
# run chi_square over all possible response options
test_uniformity <- function(
    ratings, 
    scale_levels = c(-1:7, NA), 
    include_na = TRUE) {
  
  if (include_na && any(is.na(ratings))) {
    scale_levels <- unique(c(scale_levels, NA))
    }
  
  tbl <- table(factor(ratings, levels = scale_levels),
               useNA = if (include_na) "ifany" else "no")
  
  exp <- rep(1 / length(tbl), length(tbl))
  
  res <- tryCatch({
    suppressWarnings(chisq.test(tbl, p = exp))}, 
    error = function(e) NULL)
  
  if (is.null(res) || !inherits(res, "htest")) {
    return(tibble(
      test = "Chi-square",
      df = NA_real_,
      statistic = NA_real_,
      p_value = NA_real_,
      n_missing = sum(is.na(ratings))
    ))}
  
  tibble(
    test = "Chi-square",
    df = unname(res$parameter),
    statistic = unname(res$statistic),
    p_value = res$p.value,
    n_missing = sum(is.na(ratings))
  )}
```


```{r}
uniformity_dfs <- lapply(wave_2_dfs, function(df){
  
  df %>%
    group_by(item_ID, value) %>%
    group_modify(~ test_uniformity(.x$rating)) %>%
    ungroup()  |>
    mutate(
      uniform_label = case_when(
        p_value < 0.10 ~ "non_uniform",
        TRUE ~ "uniform"))
})

uniformity_labels <- lapply(uniformity_dfs, function(df){
  df |> dplyr::select(item_ID, value, uniform_label)
})

wave_2_dfs[["wave_2_lyrics"]] <- wave_2_dfs[["wave_2_lyrics"]] |> 
  left_join(uniformity_labels[["wave_2_lyrics"]], by = c("item_ID", "value"))

wave_2_dfs[["wave_2_speeches"]] <- wave_2_dfs[["wave_2_speeches"]] |>
  left_join(uniformity_labels[["wave_2_speeches"]], by = c("item_ID", "value"))
```

```{r}
uniformity_summary <- lapply(uniformity_dfs, function(df){
  
  df|>
    dplyr::count(value, uniform_label) |> 
    pivot_wider(names_from = uniform_label, values_from = n) |>
    mutate(
      uniform = case_when(is.na(uniform) ~ 0, .default=uniform), 
      percent_uniform = round(uniform/(uniform + non_uniform)*100, 2))
})

# uniformity_gt <- bind_rows(
#   mutate(uniformity_summary[[1]], dataset = "Lyrics"),
#   mutate(uniformity_summary[[2]], dataset = "Speeches")
# ) %>%
#   gt(groupname_col = "dataset") %>%
#   tab_header(title = md("**Uniformity Results by Dataset**")) %>%
#   cols_label(
#     value = "Value",
#     uniform = "Uniform (n)",
#     non_uniform = "Non-uniform (n)",
#     percent_uniform = "% Uniform"
#   )
# 
# gtsave(uniformity_gt, here("tables", "main_uniformity_by_value_by_text.tex"))
```


```{r}
test_unimodality <- function(ratings) {
  # drop NAs
  n_missing <- sum(is.na(ratings))
  ratings <- ratings[!is.na(ratings)]
  
  
  # if too few unique ratings, skip test
  if (length(unique(ratings)) < 2) {
    return(tibble(
      test = "Dip test",
      statistic = NA_real_,
      p_value = NA_real_,
      n_obs = length(ratings), 
      n_missing = n_missing
    ))
  }
  
  # run safely
  res <- tryCatch({
    diptest::dip.test(ratings)
  }, error = function(e) NULL)
  
  # if test failed, fill with NA
  if (is.null(res) || !inherits(res, "htest")) {
    return(tibble(
      test = "Dip test",
      statistic = NA_real_,
      p_value = NA_real_,
      n_obs = length(ratings)
    ))
  }
  
  tibble(
    test = "Dip test",
    statistic = unname(res$statistic),
    p_value = res$p.value,
    n_obs = length(ratings), 
    n_missing = n_missing
  )}
```

```{r}
# https://projecteuclid.org/journals/annals-of-statistics/volume-13/issue-1/The-Dip-Test-of-Unimodality/10.1214/aos/1176346577.full
# https://academic.oup.com/jrsssc/article/34/3/320/6985177

unimodality_dfs <- lapply(wave_2_dfs, function(df){
  
  df |> 
    filter(uniform_label == "non_uniform") |>
    group_by(item_ID, value) |>
    group_modify(~ test_unimodality(.x$rating)) |>
    ungroup() |>    
    mutate(unimodal_label = case_when(
          p_value < 0.10 ~ "non_unimodal",
          TRUE ~ "unimodal"))
})

unimodality_labels <- lapply(unimodality_dfs, function(df){
  df |> dplyr::select(item_ID, value, unimodal_label)
})
```

```{r}
unimodality_summary <- lapply(unimodality_dfs, function(df){
  
  df|>
    dplyr::count(value, unimodal_label) |> 
    pivot_wider(names_from = unimodal_label, values_from = n) |>
    mutate(unimodal = case_when(is.na(unimodal) ~ 0, .default = unimodal), 
           percent_unimodal = round(unimodal/(unimodal + non_unimodal)*100, 2))

})

unimodality_gt <- bind_rows(
  mutate(unimodality_summary[[1]], dataset = "Lyrics"),
  mutate(unimodality_summary[[2]], dataset = "Speeches")
)

unimodality_gt
```



```{r}
test_bimodality <- function(ratings) {
  
  ratings <- ratings[!is.na(ratings)]
  
  if (length(unique(ratings)) < 3) {
    return(tibble(test = "Mixture (1 vs 2)", delta_BIC = NA_real_, bimodal = NA))
  }
  
  res <- tryCatch({
    fit1 <- mclust::Mclust(ratings, G = 1)
    fit2 <- mclust::Mclust(ratings, G = 2)
    tibble(
      test = "Mixture (1 vs 2)",
      delta_BIC = fit2$bic - fit1$bic,
      bimodal = fit2$bic > fit1$bic
    )
  }, error = function(e) tibble(test = "Mixture (1 vs 2)", delta_BIC = NA_real_, bimodal = NA))
  res
}
```

```{r}
bimodality_dfs <- lapply(wave_2_dfs, function(df){
  
  df |> 
    #filter(uniform_label == "non_uniform") |>
    group_by(item_ID, value) |>
    group_modify(~ test_bimodality(.x$rating)) |>
    ungroup() |>
    mutate(bimodality_label = cut(
      delta_BIC, breaks = c(-Inf, 0, 2, 6, 10, Inf),
      labels = c("unimodal", "weak", "moderate", "strong", "very strong")))

})

bimodality_labels <- lapply(bimodality_dfs, function(df){
  df |> dplyr::select(item_ID, value, bimodality_label)
})
```

```{r}
bimodality_summary <- lapply(bimodality_dfs, function(df){
  
  df|>
    dplyr::count(value, bimodality_label) |> 
    pivot_wider(names_from = bimodality_label, values_from = n)

})

bimodality_gt <- bind_rows(
  mutate(bimodality_summary[[1]], dataset = "Lyrics"),
  mutate(bimodality_summary[[2]], dataset = "Speeches")
)

bimodality_gt
```

```{r}
lyrics_labels <- merge(uniformity_labels[[1]], unimodality_labels[[1]], by = c("item_ID", "value"), all.x=T)
lyrics_labels <- merge(lyrics_labels, bimodality_labels[[1]], by = c("item_ID", "value"), all.x=T)
```

```{r}
lyrics_labels |> 
  filter(unimodal_label=="unimodal") |>
  filter(bimodality_label == "strong" | bimodality_label == "very strong")
```

