# Appendix C: Pilot Study Addendum

```{r, include=FALSE}
library("here")       # file logistics
library("tidyverse")  # code logistics
library("gt")         # rendering tables
library("patchwork")
library("rlang")
library("ggtext")     # text plots
library("ggridges")   # joy plots
```

```{r}
pilot_2_dfs <- readRDS(file = here("_data", "_participant_scores", "wave_2", "pilot_2_dfs.RDS"))

df <- pilot_2_dfs[[1]] %>% 
  select(participant_ID, 
         Q1_1, # I prefer music that contains lyrics over music that does not
         Q1_2, # My favorite songs all have lyrics
         Q1_3, # I skip songs that don't have lyrics
         Q1_4, # If a song has lyrics that I don't like, I skip it
         Q1_5, # I listen to music in languages that I dont' speak
         Q1_6, # I look at the lyrics of songs in the apps of streaming services that I use
         Q2_1  # percentage of music lib
         ) %>%
  unique()

pilot_music_lib_plot <- df %>%
  ggplot(aes(x=as.numeric(Q2_1))) +
  geom_histogram(bins=10, aes(y=..density..)) +
    geom_density() +
  xlab("Music Library Percentage") + ylab("Count") + 
  theme_classic()
```

```{r include=FALSE}
 pilot_lyric_questions_plot <- df |>
  
  select(-Q2_1) |>
  pivot_longer(cols = paste0('Q1_', seq(1, 6)), 
               names_to = 'question', 
               values_to = 'response') |>
  
  mutate(response = case_when(
    response == "Strongly agree" ~ 7, 
    response == "Agree" ~ 6, 
    response == "Somewhat agree" ~ 5, 
    response == "Neither agree nor disagree" ~ 4, 
    response == "Somewhat disagree" ~ 3, 
    response == "Disagree" ~ 2, 
    response == "Strongly disagree" ~ 1)) |>
  
  mutate(question = case_when(
    question == 'Q1_1' ~ "I prefer music that contains lyrics over music that does not", 
    question == 'Q1_2' ~ "My favorite songs all have lyrics", 
    question == 'Q1_3' ~ "I skip songs that don't have lyrics", 
    question == 'Q1_4' ~ "If a song has lyrics that I don't like, I skip it", 
    question == 'Q1_5' ~ "I listen to music in languages that I dont' speak",
    question == 'Q1_6' ~ "I look at the lyrics of songs in the apps of streaming services that I use")) |>
  
  mutate(
    question = fct_reorder(question, response, .fun = median, na.rm = TRUE)) |>

  ggplot(aes(x=response, y=question, fill = question)) +
    geom_density_ridges(alpha=.8, linewidth= .3) +
    theme_classic() +
    scale_x_continuous(breaks = seq(1, 7, 1)) +
    scale_fill_viridis_d(option = "inferno", begin = 0.15, end = 1) +
    scale_y_discrete(labels = function(x) str_wrap(x, width = 30), expand = expansion(mult = c(0.02, 0.35))) +
    ylab("") + xlab("Response") +
    theme(legend.position="none", axis.text.y = element_text(size = 12))
```

```{r}
(pilot_lyric_questions_plot | pilot_music_lib_plot) + 
  plot_annotation(tag_levels = "A")

ggsave(here("images", "pilot_lyrics_questions.pdf"), height = 5, width = 7)
```

