---
title: "wave_1_descriptives"
---

```{r}
library("here")
library("tidyverse")

data_path <- here("_data", "_participant_scores", "wave_2")
```


```{r}
# read in data
pilot_2_dfs <- readRDS(here(data_path, "pilot_2_dfs.RDS"))

# rename ethnicity column 
pilot_2_dfs[['speeches2']] <- pilot_2_dfs[['speeches2']] |> 
  rename(Ethnicity = `Ethnicity simplified`)

# subset each df
pilot_2_demog_dfs <- lapply(pilot_2_dfs, function(df){
  df <- df |> select(participant_ID, Age, Sex, `Ethnicity`) |> unique()})

# re-add spectrum to speeches2 df
pilot_2_demog_dfs[['speeches2']] <- merge(
  pilot_2_demog_dfs[['speeches2']], 
  pilot_2_dfs[['speeches2']] |> 
    select(participant_ID, `Political spectrum (us)`), by = "participant_ID")
```

```{r}
# read in data
wave_2_dfs <- readRDS(here(data_path, "wave_2_dfs.RDS"))

# subset each df
wave_2_demog_dfs <- lapply(wave_2_dfs, function(df){
  df <- df |> select(participant_ID, Age, Sex, `Ethnicity`) |> unique()})

# bring back spectrum
for (name in c("speeches1", "speeches2")) {
  wave_2_demog_dfs[[name]] <- merge(
    wave_2_demog_dfs[[name]],
    wave_2_dfs[[name]] |> 
      dplyr::select(participant_ID, `Political spectrum (us)`) |> unique(),
    by = "participant_ID"
  )
}
```


```{r}
summarize_sex <- function(df) {df|> dplyr::count(Sex) |> dplyr::mutate(percent = round(100 * n / sum(n), 1))}

lapply(pilot_2_demog_dfs, summarize_sex)
lapply(wave_2_demog_dfs, summarize_sex)
```

```{r}
summarize_age <- function(df, age_var = "Age") {
  df |>
    dplyr::summarise(
      n = dplyr::n(),
      mean_age = round(mean(.data[[age_var]], na.rm = TRUE), 1),
      sd_age = round(sd(.data[[age_var]], na.rm = TRUE), 1),
      min_age = min(.data[[age_var]], na.rm = TRUE),
      max_age = max(.data[[age_var]], na.rm = TRUE)
    )
}

lapply(list(pilot = pilot_1_demogs_df, wave = wave_1_demogs_df|>filter(!is.na(Sex))), summarize_age)
```

```{r}
summarize_ethnicity <- function(df, ethnicity_var = "Ethnicity simplified") {
  df |>
    dplyr::count(.data[[ethnicity_var]]) |>
    dplyr::mutate(percent = round(100 * n / sum(n), 1))
}

lapply(list(pilot = pilot_1_demogs_df |>
              filter(! `Ethnicity simplified` == "DATA EXPIRED"), 
            
            wave = wave_1_demogs_df|>
              filter(!is.na(`Ethnicity simplified`)) |>
              filter(! `Ethnicity simplified` == "CONSENT_REVOKED") |>
              filter(! `Ethnicity simplified` == "DATA EXPIRED")
            ), summarize_ethnicity)
```

