```{r, include=FALSE}
library("here")
library("rlang")
library("gt")
library("patchwork")
library("ggtext")
library("naniar")
library("tidyverse")
library("ggridges")

# Schwartz value inventory
values <- c("POWER", "ACHIEVEMENT", "HEDONISM",  
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION",  
            "CONFORMITY", "SECURITY")
```

```{r, include=FALSE}
data_path <- here("_data", "_participant_scores", "wave_2")

# read in data
wave_2_dfs <- readRDS(here(data_path, "wave_2_dfs.RDS"))

# subset each df
wave_2_demog_dfs <- lapply(wave_2_dfs, function(df){
  df <- df |> select(participant_ID, Age, Sex, `Ethnicity`) |> unique()})

# bring back spectrum
for (name in c("speeches1", "speeches2")) {
  wave_2_demog_dfs[[name]] <- merge(
    wave_2_demog_dfs[[name]],
    wave_2_dfs[[name]] |> 
      dplyr::select(participant_ID, `Political spectrum (us)`) |> unique(),
    by = "participant_ID")}

rm(wave_2_dfs)

# convert age to numeric
wave_2_demog_dfs <- lapply(wave_2_demog_dfs, function(df){df|>mutate(Age = as.numeric(Age))})

# recode Asian ethnicity
wave_2_demog_dfs <- lapply(wave_2_demog_dfs, function(df){
  df |> mutate(Ethnicity = case_when(
    Ethnicity == "East Asian" | Ethnicity == "South East Asian" | Ethnicity == "South Asian" ~ "Asian", 
    .default = Ethnicity))})

wave_labels <- c(
  lyrics1   = "Main 1 (Lyrics 1)",
  lyrics2   = "Main 2 (Lyrics 2)",
  speeches1 = "Main 3 (Speeches 1)",
  speeches2 = "Main 4 (Speeches 2)"
)
```

```{r, include=FALSE}
format_apa_table <- function(gt_tbl, title, subtitle = NULL) {
  gt_tbl %>%
    tab_header(
      title = title, 
      subtitle = subtitle
    ) %>%
    tab_options(
      table.font.names                  = c("Times New Roman", "Times", "serif"),
      table.border.top.width            = 1,  # top line
      column_labels.border.bottom.width = 1,  # header line
      table.border.bottom.width         = 1,  # bottom line
      table_body.hlines.width           = 0,  # no row lines
      data_row.padding                  = px(2)
    )
}
```

```{r include=FALSE}
summarize_demographics <- function(df, study_name) {
  df %>%
    summarise(
      Study   = study_name,
      N       = n(),
      Age_M   = mean(Age, na.rm = TRUE),
      Age_SD  = sd(Age, na.rm = TRUE),
      Age_Min  = min(Age, na.rm = TRUE),
      Age_Max  = max(Age, na.rm = TRUE),
      Female_p  = mean(Sex == "Female", na.rm = TRUE) * 100) %>%
  mutate(
    `Age M (SD)` = sprintf("%.1f (%.1f)", Age_M, Age_SD),
    `Age range`  = sprintf("%d–%d", round(Age_Min), round(Age_Max)),
    `% Female`   = round(Female_p, 1)) %>%
  select(Study, N, `Age M (SD)`, `Age range`, `% Female`)
}

summarize_ethnicity <- function(df, study_name) {
  df %>%
    count(Ethnicity) %>%
    mutate(
      pct = 100 * n / sum(n),
      value = paste0(n, " (", round(pct, 1), "%)")
    ) %>%
    select(Ethnicity, value) %>%
    pivot_wider(names_from = Ethnicity, values_from = value) %>%
    mutate(Study = study_name, .before = 1)
}


summarize_spectrum <- function(df, study_name) {
  df %>%
    count(`Political spectrum (us)`) %>%
    mutate(
      pct = 100 * n / sum(n),
      value = paste0(n, " (", round(pct, 1), "%)")
    ) %>%
    select(`Political spectrum (us)`, value) %>%
    pivot_wider(names_from = `Political spectrum (us)`, values_from = value) %>%
    mutate(Study = study_name, .before = 1)
}
```

### Methods

#### Table 3: Sample Descriptives

```{r}
wave_demog_tbl <- imap_dfr(
  wave_2_demog_dfs,
  ~ summarize_demographics(.x, wave_labels[[.y]] %||% .y))

# main table
table <- wave_demog_tbl %>%
  gt() %>%
  cols_align(align = "left",  columns = c(Study)) %>%
  cols_align(align = "center", columns = c(N, `% Female`, `Age range`, `Age M (SD)`)) %>%
  fmt_number(columns = `% Female`, decimals = 1)

table  
  
gtsave(table, here("tables", "main_demographics.tex"))

rm(table)
```

#### Table 4a: Ethnicity Descriptives

```{r}
wave_ethnicity_tbl <- imap_dfr(
  wave_2_demog_dfs,
  ~ summarize_ethnicity(.x, wave_labels[[.y]] %||% .y))

table <- wave_ethnicity_tbl |>
  gt() %>%
  cols_label(
    `Black/African American` = html("Black/<br>African American"),
    `Latino/Hispanic`        = html("Latino/<br>Hispanic"),
    Asian                    = "Asian",
    White                    = "White") |>
  
  fmt_number(columns = -Study, decimals = 1) %>%
  
  cols_align(align = "center", 
             columns = c(Asian, `Black/African American`, 
                         `Latino/Hispanic`, White))

table

gtsave(table, here("tables", "main_ethnicity.tex"))

rm(table)
```

#### Table 4b: Spectrum descriptives

```{r}
wave_spectrum_tbl <- imap_dfr(
  wave_2_demog_dfs[3:4],
  ~ summarize_spectrum(.x, wave_labels[[.y]] %||% .y))

table <- wave_spectrum_tbl |>
  
  gt() %>%
  
  fmt_number(
    columns = -Study, 
    decimals = 1
  ) %>%
  
  cols_align(align = "center", columns = c(Conservative, Liberal, Moderate))

table

gtsave(table, here("tables", "main_political_leaning.tex"))

rm(table)
```

```{r include=FALSE}
wave_2_dfs <- readRDS(here("_data", "_intermediary_data", "wave_2_dfs.RDS"))

lyrics_df    <- wave_2_dfs$wave_2_lyrics
speeches_df  <- wave_2_dfs$wave_2_speeches

# there's a duplicate:
bind_rows(
  Lyrics = lyrics_df |> select(item_ID, participant_ID, value, rating),
  Speeches = speeches_df |> select(item_ID, participant_ID, value, rating),
  .id = "text_type"
) |>
  count(text_type, item_ID, participant_ID, value) |>
  filter(n > 1)
```

```{r include=FALSE}
# summarize_ratings <- function(df) {
# 
#   df <- df |> select(participant_ID, item_ID) |> unique()
#   
#   
#   # total number of rows = total number of ratings
#   total_ratings <- nrow(df)
#   
#   item_summary <- df |> 
#     group_by(item_ID) |> 
#     summarise(n_ratings = n()) |> 
#     summarize(mean_n_ratings = mean(n_ratings), 
#               sd_n_ratings = sd(n_ratings)) |> 
#     ungroup()
#   
#   participant_summary <- df |>
#     group_by(participant_ID) |>     
#     summarise(n_ratings = n()) |> 
#     summarize(mean_n_ratings = mean(n_ratings), 
#               sd_n_ratings = sd(n_ratings)) |> 
#     ungroup()
#     
#   list(
#     total_ratings = total_ratings,
#     item_summary  = item_summary, 
#     participant_summary = participant_summary
#   )
# }
```

#### In-text: ratings / items

```{r}
summarize_ratings <- function(df) {

  df <- df |> 
    select(participant_ID, item_ID) |> 
    distinct()

  total_ratings <- nrow(df)

  item_counts <- df |>
    count(item_ID, name = "n_ratings_item")

  participant_counts <- df |>
    count(participant_ID, name = "n_ratings_participant")

  n_items <- nrow(item_counts)
  median_item <- median(item_counts$n_ratings_item)
  median_participant <- median(participant_counts$n_ratings_participant)

  latex_sentence <- sprintf(
    "In total, we collected %s ratings of %s items. The median number of ratings per item was %s, and the median number of ratings per participant was %s.",
    total_ratings, n_items, median_item, median_participant
  )
  
  latex_sentence
}
summarize_ratings(lyrics_df)
summarize_ratings(speeches_df)
```

### Results

#### Figure 9: Ratings by Value / Text type

```{r}
plot_value_histograms_with_na <- function(df, text_label, option) {
  
  df <- df |> mutate(
    value = factor(value, levels = sort(unique(value))), 
    response = ifelse(is.na(rating), "NA", as.character(rating)),
    response = factor(
      response, 
      levels = c("NA", "-1", "0", "1", "2", "3", "4", "5", "6", "7")))
  
  # Compute % NA per value
  na_annot <- df %>%
    group_by(value) %>%
    summarise(na_pct = mean(is.na(rating)) * 100, .groups = "drop")
  
  ggplot(df, aes(x = response, fill = value)) +
    geom_bar() +
    facet_wrap(~ value, ncol = 2) +
    geom_text(
      # this produces the label
      data = na_annot, aes(label = sprintf("NA: %.1f%%", na_pct)),
      x = 5, y = 3000, 
      size = 3.5) +
    scale_fill_viridis_d(option = option) +
    scale_x_discrete(drop = F) +
    scale_y_continuous(limits = c(0, 4800)) +
    theme_classic() +
    labs(
      title = paste(text_label),
      x = "Response", y = "") +
    theme(strip.text = element_text(face = "bold"),
          axis.text.y = element_text(size = 12), 
          legend.position = "none")
}

p1 <- plot_value_histograms_with_na(wave_2_dfs$wave_2_lyrics, "Lyrics", option = "inferno")
p2 <- plot_value_histograms_with_na(wave_2_dfs$wave_2_speeches, "Speeches", option = "D")

hist_plot <- (p1 | p2) + plot_annotation(tag_levels = "A")
hist_plot
ggsave(here("images", "main_histogram_by_text.pdf"))
```

```{r include=FALSE}
#(na_plot / hist_plot) + plot_annotation(tag_levels = "A")
#ggsave(here("images", "main_dist_by_text.pdf"), width = 8, height = 8)
```
