---
title: "quiz analysis"
author: "Andrew M. Demetriou"
---

```{r}
library("here")
library("tidyverse")
library("patchwork")
library("gt")
library("ggtext")

quiz_df <- readRDS(here("_data", "_participant_scores", "wave_2", "wave_2_quiz_df.RDS"))

quiz_df <- quiz_df |>
  
    select(-Ethnicity) |> 
  
    # convert to numeric
    mutate(
      Quiz_1 = as.numeric(Quiz_1), 
      Quiz_2 = as.numeric(Quiz_2), 
      Quiz_3 = as.numeric(Quiz_3)) |>
    
    # set as ordered factors
    mutate(
      Quiz1 = ifelse(is.na(Quiz1), "NA", as.character(Quiz1)),
      Quiz1 = factor(Quiz1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      
      Quiz2 = ifelse(is.na(Quiz2), "NA", as.character(Quiz2)),
      Quiz2 = factor(Quiz2, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      
      Quiz3 = ifelse(is.na(Quiz3), "NA", as.character(Quiz3)),
      Quiz3 = factor(Quiz3, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE)) |>
  
  rename(Study = wave)
```

```{r}
quiz_df
```


```{r}
summarize_study <- function(df) {
  df %>%
    summarise(
      Q1 = sprintf("%d (%.1f%%)", sum(Quiz_1, na.rm = TRUE),
                      mean(Quiz_1, na.rm = TRUE) * 100),
      Q2 = sprintf("%d (%.1f%%)", sum(Quiz_2, na.rm = TRUE),
                      mean(Quiz_2, na.rm = TRUE) * 100),
      Q3 = sprintf("%d (%.1f%%)", sum(Quiz_3, na.rm = TRUE),
                      mean(Quiz_3, na.rm = TRUE) * 100)
    ) %>%
    
    pivot_longer(everything(), names_to = "Question", values_to = "N_percent")
}

# create a list of dataframes, one for each study
quiz_dfs <- split.data.frame(quiz_df, quiz_df$Study)


lapply(quiz_dfs, summarize_study) %>%
  
  bind_rows(.id = "Study") %>%
  
  pivot_wider(names_from = Study, values_from = N_percent) %>%
  
  gt() %>%
  
  tab_header(
    title = md("**Table 2a**"),
    subtitle = md("*Main Study Waves: Overall Quiz Item Correctness*")
  ) %>%
  cols_label(
    Question = "Item",
    lyrics_1 = "Wave: Lyrics 1",
    lyrics_2 = "Wave: Lyrics 2",
    speeches_1 = "Wave: Speeches 1",
    speeches_2 = "Wave: Speeches 2"
  ) %>%
  cols_align(
    align = "center",
    columns = everything()
  ) %>%
  cols_width(everything() ~ px(100)) |>
  tab_options(
    table.font.size = 12,
    heading.align = "left",
    table.border.top.width = px(0),       # remove top rule
    table.border.bottom.width = px(0),    # remove bottom rule
    table_body.hlines.width = px(0),   # removes horizontal lines inside body
    table_body.vlines.width = px(0)    # removes vertical lines
  ) %>%
  tab_source_note(
    
    md("*Note.* Entries are number and percentage of participants who answered correctly. Quiz responses were used to exclude participants in main studies."))

```


```{r}
plot_stacked_bars <- function(df, column, option="C") {
  
  df |>
    ggplot(aes({{column}}, fill = as.factor(Study))) + 
    #ggplot(aes(Quiz2, fill = as.factor(Study))) + 
    geom_bar() +
    scale_fill_viridis_d(
      option = option,
      name = "Main Study: ",
      labels = c("lyrics1" = "Lyrics #1", 
                 "lyrics2" = "Lyrics #2", 
                 "speeches1"  = "Speeches #1", 
                 "speeches2"  = "Speeches #2")) +
    scale_y_continuous(limits = c(0, 500)) +
    scale_x_discrete(drop = FALSE)
}

apa_theme <- 
  theme_classic(base_size = 12, base_family = "sans") +
  theme(
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 10),
    legend.position = "bottom",          
    legend.title = element_text(size = 11),
    legend.text  = element_text(size = 10),
    panel.border = element_blank(),      
    axis.line = element_line(color = "black"),
    strip.background = element_blank(),  
    strip.text = element_text(size = 11)
  )
```

```{r}
df <- quiz_df

p1 <- plot_stacked_bars(df|>filter(Quiz_2=="0"), Quiz2, option = "C") +
  xlab("Q2 Responses") + ylab("Count") +
  apa_theme

p2 <- plot_stacked_bars(df|>filter(Quiz_3=="0"), Quiz3, option = "C") +
  xlab("Q3 Responses") + ylab("") +
  apa_theme

(p1 | p2) +
    plot_layout(guides = "collect") +
    plot_annotation(
      title = "**Figure 2a**",
      subtitle = "*Incorrect Participant Quiz Responses*", 
      caption = "*Note*. Bars represent raw counts of responses, including NA as a category, for all participants that answered incorrectly. Colors represent specific study. Participant pool includes participants that were ultimately screened out for incorrectly answering 2 or more quiz questions.") &
    theme(legend.position = "bottom", 
          plot.title = element_markdown(hjust = 0), 
          plot.subtitle = element_markdown(hjust = 0), 
          plot.caption = element_markdown(hjust = 0))
```
```{r}
df <- quiz_df |> filter(Status=="APPROVED")

p1 <- plot_stacked_bars(df|>filter(Quiz_2=="0"), Quiz2, option = "C") +
  xlab("Q2 Responses") + ylab("Count") +     scale_y_continuous(limits = c(0, 300)) +
  apa_theme

p2 <- plot_stacked_bars(df|>filter(Quiz_3=="0"), Quiz3, option = "C") +
  xlab("Q3 Responses") + ylab("") +     scale_y_continuous(limits = c(0, 300)) +
  apa_theme

(p1 | p2) +
    plot_layout(guides = "collect") +
    plot_annotation(
      title = "**Figure 2b**",
      subtitle = "*Incorrect Participant Quiz Responses*", 
      caption = "*Note*. Bars represent raw counts of responses, including NA as a category, for all participants that answered incorrectly. Colors represent specific study. Participant pool includes only participants that were approved for correctly answering 2 or more quiz questions.") &
    theme(legend.position = "bottom", 
          plot.title = element_markdown(hjust = 0), 
          plot.subtitle = element_markdown(hjust = 0), 
          plot.caption = element_markdown(hjust = 0))
```

