---
title: "summary reliabilities"
author: "andrew demetriou"
---

AIM: estimate reliability by value for primary study dataset

```{r setup, include=FALSE}
library('here')                 # file logistics
library('dplyr')                # data manipulation
library('tidyr')                # data manipulation
library('tidyverse')            # code logistics
library('cowplot')
library('viridis')
library('patchwork')

values <- c("POWER", "ACHIEVEMENT", "HEDONISM",  
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION",  
            "CONFORMITY", "SECURITY")
```


```{r}
# output file path
file_path <- here("_data", "_intermediary_data")

# read in data
wave_2_dfs <- readRDS(here("_data", "_participant_scores", "wave_2", "wave_2_dfs.RDS"))

# merge ethnicity
wave_2_dfs <- lapply(wave_2_dfs, function(df){
  df %>% 
    filter(item_ID != "attention") %>%
    mutate(Ethnicity = case_when(
      Ethnicity == "South East Asian" ~ "Asian",
      Ethnicity == "South Asian" ~ "Asian",
      Ethnicity == "East Asian" ~ "Asian",
      Ethnicity == "CONSENT_REVOKED" ~ NA, 
      .default = Ethnicity))
})

# rename variables
wave_2_dfs[1:2] <- lapply(wave_2_dfs[1:2], function(df){
  df %>% select(item_ID, participant_ID, Ethnicity, all_of(values))
})

wave_2_dfs[3:4] <- lapply(wave_2_dfs[3:4], function(df){
  df %>% rename(Spectrum = `Political spectrum (us)`) %>%
    select(item_ID, participant_ID, Ethnicity, Spectrum, all_of(values))
})

wave_2_dfs <- list(
  lyrics = bind_rows(wave_2_dfs[[1]], wave_2_dfs[[2]]), 
  speeches = bind_rows(wave_2_dfs[[3]], wave_2_dfs[[4]]) 
)

# subsample by participant characteristics
ethnicity_subsample_lists <- lapply(wave_2_dfs, function(df){
  c(list(overall = df), split(df, df$Ethnicity))
})

spectrum_subsample_lists <- lapply(wave_2_dfs[2], function(df){
  c(list(overall = df), split(df, df$Spectrum))
})

wave_2_0na_dfs <- imap(wave_2_dfs, ~ {
  .x %>%
    mutate(across(where(is.numeric), ~replace_na(., 0)))
})
```

```{r}
plot_sd_histogram <- function(df){ 
  
  # pivot to long format & estimate mean/sd per song/value
  df <- df %>%
    pivot_longer(cols = all_of(values), names_to = "value", values_to = "rating") %>%
    group_by(item_ID, value) %>%
    summarize(mean = mean(rating, na.rm=T), sd = sd(rating, na.rm=T)) %>% ungroup()

  mean_sd <- mean(df$sd, na.rm=T)
  sd_sd <- sd(df$sd, na.rm=T)
  
  df %>% ggplot(aes(sd)) +
    geom_histogram(alpha=.7, bins=50, aes(fill="black")) +
    theme_minimal() +
    geom_vline(xintercept = c(mean_sd - sd_sd, mean_sd + sd_sd), 
               color = "red", linetype = "dashed") +
    geom_vline(xintercept = mean_sd, color = "red") +
    #scale_x_continuous(limits = c(0, 4.5)) +
    #scale_y_continuous(limits = c(0, 800)) +
    ggtitle(paste0("Mean SD: ", round(mean_sd, 2), " ; sd of SD: ", round(sd_sd, 2)))
  
  }

plot_sd_hist_pairs <- function(df1, df2, color1, color2){
  
  p1 <- plot_sd_histogram(df1)
  p2 <- plot_sd_histogram(df2)
  
  p1 <- p1 + scale_fill_manual(values = color1) + theme(legend.position = "none")
  p2 <- p2 + scale_fill_manual(values = color2) + theme(legend.position = "none")
  
  (p1/ p2)
  
}
```


```{r}
my_colors = viridis(10, option= "magma")

plot_sd_hist_pairs(wave_2_dfs[['lyrics']], 
                   wave_2_0na_dfs[['lyrics']], 
                   my_colors[[2]], my_colors[[3]])

plot_sd_hist_pairs(wave_2_dfs[['speeches']], 
                   wave_2_0na_dfs[['speeches']], 
                   my_colors[[4]], my_colors[[5]])
```

```{r}
get_mean_sd <- function(subsample_lists){

  imap(subsample_lists, function(df_list, data_name){
    
    
    # estimate mean and sd, with NAs included vs. converted to 0
    imap(df_list, function(df, var_name){
      
      df <- df %>% pivot_longer(cols = all_of(values), names_to = "value", values_to = "rating")
      na_df <- df %>% mutate(across(where(is.numeric), ~replace_na(., 0)))
      
      summary_df <- df %>% group_by(item_ID, value) %>% 
        summarize(mean = mean(rating, na.rm=T), sd = sd(rating, na.rm=T), 
                  .groups = "drop") %>% mutate(na = "present")
            
      summary_na_df <- na_df %>% group_by(item_ID, value) %>% 
        summarize(mean = mean(rating, na.rm=T), sd = sd(rating, na.rm=T), 
                  .groups = "drop") %>% mutate(na = "as 0")
      
      mean_sd <- mean(summary_df$sd, na.rm=T)
      sd_sd <- sd(summary_df$sd, na.rm=T)

      mean_0na_sd <- mean(summary_na_df$sd, na.rm=T)
      sd_0na_sd <- sd(summary_na_df$sd, na.rm=T)
      
      # results tibble
      tibble(
        subroup = var_name,
        mean_sd = mean_sd,
        sd_sd = sd_sd, 
        mean_0na_sd = mean_0na_sd,  
        sd_0na_sd = sd_0na_sd
      )
    }) %>% bind_rows() %>% mutate(data_type = data_name)
    
  }) %>% bind_rows() %>% 
    pivot_wider(names_from = data_type, 
                values_from = c(mean_sd, mean_0na_sd, sd_sd, sd_0na_sd))
  
} 

bind_rows(get_mean_sd(ethnicity_subsample_lists), get_mean_sd(spectrum_subsample_lists))
```


```{r}
plot_precision <- function(df){
  
  # pivot to long format & estimate mean/sd per song/value
  df <- df %>%
    pivot_longer(cols = all_of(values), names_to = "value", values_to = "rating") %>%
    group_by(item_ID, value) %>%
    summarize(mean = mean(rating, na.rm=T), sd = sd(rating, na.rm=T)) %>% ungroup()
  
  
  p1 <- df %>% ggplot(aes(mean, sd, color=value)) + 
    geom_point(alpha=.5) + 
    scale_color_viridis_d(option = "magma") +
    theme_minimal() + 
    scale_y_continuous(limits = c(0,5)) +
    scale_x_continuous(limits = c(-1,7), breaks = c(-1,0,1,2,3,4,5,6,7)) 
}
```

```{r}
p1 <- plot_precision(wave_2_dfs[[1]]) +
  labs(title = "NAs removed") +
  theme(legend.position = "none")

p2 <- plot_precision(wave_2_0na_dfs[[1]]) + 
  labs(title = "NAs as 0")

(p1+p2) + plot_layout(guides="collect") + plot_annotation(title = "Lyrics")

p1 <- plot_precision(wave_2_dfs[[2]]) +
  labs(title = "NAs removed")

p2 <- plot_precision(wave_2_0na_dfs[[2]]) + 
  labs(title = "NAs as 0")

(p1+p2) + plot_layout(guides="collect") + plot_annotation(title = "Speeches")
```


```{r}
plot_na_percentage <- function(df){
  
  # long format
  df <- df %>%
    pivot_longer(cols = all_of(values), names_to = "value", values_to = "rating") %>%
    group_by(item_ID, value)

  # compute percentage of NA responses per item
  percent_na_df <- df %>% 
    group_by(value, item_ID) %>% 
    mutate(is_na = is.na(rating)) %>% 
    count(is_na) %>% 
    mutate(percent = n / sum(n)*100) %>%
    ungroup()
  
  # plot histograms
  my_colors = viridis(10, option= "magma")

  p1 <- percent_na_df %>%  
    ggplot(aes(x=percent, fill=is_na)) +
    geom_histogram(position="identity", alpha=.8, bins=25) +
    scale_fill_manual(values = c(my_colors[5], my_colors[8]), labels=c("Present", "NA")) +
    theme_minimal()
    
  p2 <- p1 + facet_wrap(~value, ncol = 2) + theme(legend.position = "none")
  
  plot_grid(p1, p2)
}
```

```{r}
lapply(wave_2_dfs, plot_na_percentage)
```
