## Main Studies

### Participants

```{r, include=FALSE}
library("here")
library("tidyverse")
library("rlang")
library("gt")
library("patchwork")
library("ggtext")
```

```{r, include=FALSE}
quiz_df <- readRDS(here("_data", "_participant_scores", "wave_2", "wave_2_quiz_df.RDS"))

quiz_df <- quiz_df |>

    select(-Ethnicity) |>

    # convert to numeric
    mutate(
      Quiz_1 = as.numeric(Quiz_1),
      Quiz_2 = as.numeric(Quiz_2),
      Quiz_3 = as.numeric(Quiz_3)) |>

    # set as ordered factors
    mutate(
      Quiz1 = ifelse(is.na(Quiz1), "NA", as.character(Quiz1)),
      Quiz1 = factor(Quiz1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),

      Quiz2 = ifelse(is.na(Quiz2), "NA", as.character(Quiz2)),
      Quiz2 = factor(Quiz2, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),

      Quiz3 = ifelse(is.na(Quiz3), "NA", as.character(Quiz3)),
      Quiz3 = factor(Quiz3, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE)) |>

  rename(Study = wave)
```

```{r include=FALSE}
summarize_study <- function(df) {
  df %>%
    summarise(
      Q1 = sprintf("%d (%.1f%%)", sum(Quiz_1, na.rm = TRUE),
                      mean(Quiz_1, na.rm = TRUE) * 100),
      Q2 = sprintf("%d (%.1f%%)", sum(Quiz_2, na.rm = TRUE),
                      mean(Quiz_2, na.rm = TRUE) * 100),
      Q3 = sprintf("%d (%.1f%%)", sum(Quiz_3, na.rm = TRUE),
                      mean(Quiz_3, na.rm = TRUE) * 100)
    ) %>%

    pivot_longer(everything(), names_to = "Question", values_to = "N_percent")
}
```

```{r}
plot_bars <- function(df,
                      column1, # responses
                      column2, # color
                      option) {

  df |>
    mutate({{column2}} := fct_recode(as.factor({{column2}}),
                                     "Correct"   = "1","Incorrect" = "0")) |>

    ggplot(aes({{column1}}, fill = as.factor({{column2}}))) +
    geom_bar() +
    scale_fill_viridis_d(option = option,
                         name = "Response:") +
    scale_y_continuous(limits = c(0, 1250)) +

    scale_x_discrete(drop = FALSE)}
```

```{r}
# including those that were screened out
df <- quiz_df

p1 <- plot_bars(df, Quiz1, Quiz_1, option = "D") +
  xlab("Q1 Responses") + ylab("Count") +
  apa_theme

p2 <- plot_bars(df, Quiz2, Quiz_2, option = "D") +
  xlab("Q2 Responses") + ylab("Count") +
  apa_theme

p3 <- plot_bars(df, Quiz3, Quiz_3, option = "D") +
  xlab("Q3 Responses") + ylab("") +
  apa_theme

(p1 | p2 | p3) +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom",
        plot.title = element_markdown(hjust = 0),
        plot.subtitle = element_markdown(hjust = 0),
        plot.caption = element_markdown(hjust = 0))

ggsave(here("images", "main_quiz_correctness.pdf"))
```
