---
title: "quiz analysis"
author: "Andrew M. Demetriou"
---

```{r}
library("here")
library("tidyverse")
library("patchwork")
library("gt")
library("ggtext")

pilot_2_dfs <- readRDS(file = here("_data", "_participant_scores", "wave_2", "pilot_2_dfs.RDS"))
  
  
# subset pilot dfs
#pilot_2_dfs <- lapply(pilot_2_dfs, function(df){
quiz_dfs <- lapply(pilot_2_dfs, function(df){
 
  df |>
    select(participant_ID, 
           Quiz1_1, Quiz2_1, Quiz3_1, 
           Quiz1, Quiz2, Quiz3) |>
    
    unique() |>
    
    # recalculate Quiz 3
    mutate(Quiz3 = case_when(
      Quiz3_1 == "-1" | Quiz3_1 == "0" | Quiz3_1 == "1"  ~ "1", 
      .default = "0")) |>
    
    # convert to numeric
    mutate(
      Quiz1 = as.numeric(Quiz1), 
      Quiz2 = as.numeric(Quiz2), 
      Quiz3 = as.numeric(Quiz3)) |>
    
    mutate(
      Quiz2_1 = ifelse(is.na(Quiz2_1), "NA", as.character(Quiz2_1)),
      Quiz2_1 = factor(Quiz2_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      Quiz3_1 = ifelse(is.na(Quiz3_1), "NA", as.character(Quiz3_1)),
      Quiz3_1 = factor(Quiz3_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE)
)})
```

```{r}
# pilot_2_dfs <- readRDS(file = here("_data", "_participant_scores", "wave_2", "pilot_2_dfs.RDS"))
# 
# # attention check
# attention_dfs <- lapply(pilot_2_dfs, function(df){
#   
#   df %>% 
#     select(
#       
#       participant_ID, item_ID, 
#       POWER, ACHIEVEMENT, HEDONISM, 
#       STIMULATION, SELF, UNIVERSALISM, 
#       BENEVOLENCE, TRADITION, 
#       CONFORMITY, SECURITY, w, f) %>%
#     
#     filter(grepl("attention", item_ID))
# })
# 
# 
# # lyrics was w variable
# attention_dfs[['lyrics']] <- attention_dfs[['lyrics']] %>%
#   select(-item_ID) %>%
#   mutate(f = if_else(f == "No", 1, 0), 
#          w = if_else(w == "Yes", 1, 0)) 
# 
# # speeches doesn't
# attention_dfs[['speeches1']] <- attention_dfs[['speeches1']] %>%
#   select(-item_ID) %>%
#   mutate(f = if_else(f == "No", 1, 0))
# 
# # speeches2 does
# attention_dfs[['speeches2']] <- attention_dfs[['speeches2']] %>%
#   select(-item_ID) %>%
#   mutate(f = if_else(f == "No", 1, 0), 
#          w = if_else(w == "Republican", 1, 0)) 


# df <- attention_dfs[["lyrics"]]
# df <- attention_dfs[["speeches1"]]
# df <- attention_dfs[["speeches2"]]
```



```{r}
summarize_study <- function(df) {
  df %>%
    summarise(
      Q1 = sprintf("%d (%.1f%%)", sum(Quiz1, na.rm = TRUE),
                      mean(Quiz1, na.rm = TRUE) * 100),
      Q2 = sprintf("%d (%.1f%%)", sum(Quiz2, na.rm = TRUE),
                      mean(Quiz2, na.rm = TRUE) * 100),
      Q3 = sprintf("%d (%.1f%%)", sum(Quiz3, na.rm = TRUE),
                      mean(Quiz3, na.rm = TRUE) * 100)
    ) %>%
    
    pivot_longer(everything(), names_to = "Question", values_to = "N_percent")
}

#lapply(pilot_2_dfs, summarize_study) %>%
lapply(quiz_dfs, summarize_study) %>%
  
  bind_rows(.id = "Study") %>%
  
  pivot_wider(names_from = Study, values_from = N_percent) %>%
  
  gt() %>%
  
  tab_header(
    title = md("**Table 4**"),
    subtitle = md("*Pilot Studies: Quiz Item Correctness*")
  ) %>%
  cols_label(
    Question = "Item",
    lyrics = "Pilot: Lyrics",
    speeches1 = "Pilot: Speeches 1",
    speeches2 = "Pilot: Speeches 2"
  ) %>%
  cols_align(
    align = "center",
    columns = everything()
  ) %>%
  cols_width(everything() ~ px(100)) |>
  tab_options(
    table.font.size = 12,
    heading.align = "left",
    table.border.top.width = px(0),       # remove top rule
    table.border.bottom.width = px(0),    # remove bottom rule
    table_body.hlines.width = px(0),   # removes horizontal lines inside body
    table_body.vlines.width = px(0)    # removes vertical lines
  ) %>%
  tab_source_note(
    
    md("*Note.* Entries are number and percentage of participants who answered correctly. Quiz responses were not used to exclude participants in pilot studies."))

```





```{r}
df <- bind_rows(quiz_dfs, .id = "Pilot")

plot_stacked_bars <- function(df, column, option) {
  
  df |>
    ggplot(aes({{column}}, fill = as.factor(Pilot))) + 
    geom_bar() +
    scale_fill_viridis_d(
      option = option,
      name = "Pilot Study: ",
      labels = c("lyrics" = "Lyrics", 
                 "speeches1"  = "Speeches #1", 
                 "speeches2"  = "Speeches #2")) +
    scale_y_continuous(limits = c(0, 225)) +
    scale_x_discrete(drop = FALSE)
}
```

```{r}
apa_theme <- 
  theme_classic(base_size = 12, base_family = "sans") +
  theme(
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 10),
    legend.position = "bottom",          
    legend.title = element_text(size = 11),
    legend.text  = element_text(size = 10),
    panel.border = element_blank(),      
    axis.line = element_line(color = "black"),
    strip.background = element_blank(),  
    strip.text = element_text(size = 11)
  )
```


```{r}
p1 <- plot_stacked_bars(df, Quiz1_1, option = "C") +
  xlab("Q1 Responses") + ylab("Count") +
  apa_theme

p2 <- plot_stacked_bars(df, Quiz2_1, option = "C") +
  xlab("Q2 Responses") + ylab("Count") +
  apa_theme

p3 <- plot_stacked_bars(df, Quiz3_1, option = "C") +
  xlab("Q3 Responses") + ylab("") +
  apa_theme

(p1 | p2 | p3) +
    plot_layout(guides = "collect") +
    plot_annotation(
      title = "**Figure 10**",
      subtitle = "*Participant Quiz Responses*", 
      caption = "*Note*. Bars represent raw counts of responses, including NA as a category, for all participants that answered incorrectly. Colors represent specific pilot study.") &
    theme(legend.position = "bottom", 
          plot.title = element_markdown(hjust = 0), 
          plot.subtitle = element_markdown(hjust = 0), 
          plot.caption = element_markdown(hjust = 0))
```
