---
title: "R Notebook"
---

```{r}
library("here")         # file logistics
library("lme4")         # mixed effects metric
library("lmerTest")     # p values
library("ordinal")      # mixed effects ordinal
library("tidyverse")    # code logistics
library("emmeans")      # estimated marginal means
library("patchwork")    # merging plots
library("performance")  # estimate pseudo R2
library("gt")           # latex table

# Schwartz value inventory
values <- c("POWER", "ACHIEVEMENT", "HEDONISM",  
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION",  
            "CONFORMITY", "SECURITY")

# TO "CENTER" CATEGORICAL PREDICTORS, set the coding to contr.sum (deviations from the average)
options(scipen = 999, contrasts = c("contr.sum", "contr.poly"))
```

```{r}
# read in likert models
wave_2_lyrics_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_lyrics_mods.RDS"))
wave_2_speeches_ethnicity_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_ethnicity_mods.RDS"))
wave_2_speeches_spectrum_mods <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_spectrum_mods.RDS"))
```

```{r}
# predicted values from models in the same likert scale space (-1 to 7)
mypredict <- function(m, newdata = NULL, ...) {
  UseMethod("mypredict", m)
}
mypredict.lmerModLmerTest <- function(m, newdata = NULL, ...) {
  if(is.null(newdata)) newdata <- model.frame(m)
  predict(m, newdata = newdata, ...)
}
mypredict.clmm <- function(m, newdata = NULL, ...) {
  if(is.null(newdata)) newdata <- model.frame(m)
  left_join(newdata, as.data.frame(ref_grid(m, mode = "mean.class")))$mean.class-2
}
mypredict.glmerMod <- function(m, newdata = NULL, ...) {
  if(is.null(newdata)) newdata <- model.frame(m)
  predict(m, newdata = newdata, type="response")*8-1
}
```

```{r}
# add predictions from models to dataframes
predict_by_rating <- function(mods) {
  # collect all models
  models <- list(
    lmer = mods$lmer,
    clmm = mods$clmm,
    glmer = mods$glmer
  )

  # loop over model types
  yhat_dfs <- lapply(names(models), function(n) {
    m <- models[[n]]
    df <- model.frame(m)
    y <- df$rating
    yhat <- mypredict(m, newdata = df)
    df %>% mutate(y = y, yhat = yhat)
  })

  names(yhat_dfs) <- names(models)
  return(yhat_dfs)
}
```


```{r}
# add predicted values to df and save objects
# this takes some time to run

wave_2_lyrics_yhat_dfs <- predict_by_rating(wave_2_lyrics_mods)
# rescale so y values are on a scale of -1 to 7
wave_2_lyrics_yhat_dfs[["glmer"]] <- wave_2_lyrics_yhat_dfs[["glmer"]] |> mutate(y=y*8-1)

saveRDS(wave_2_lyrics_yhat_dfs, here("_data", "_intermediary_data", "models", "wave_2_lyrics_yhat_dfs.RDS"))



wave_2_speeches_ethnicity_yhat_dfs <- predict_by_rating( wave_2_speeches_ethnicity_mods)
# rescale so y values are on a scale of -1 to 7
wave_2_speeches_ethnicity_yhat_dfs[["glmer"]] <- wave_2_speeches_ethnicity_yhat_dfs[["glmer"]] |> mutate(y=y*8-1)

saveRDS(wave_2_speeches_ethnicity_yhat_dfs, here("_data", "_intermediary_data", "models", "wave_2_speeches_ethnicity_yhat_dfs.RDS"))
```

```{r}
# load dataframes with predictions
wave_2_lyrics_yhat_dfs <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_lyrics_yhat_dfs.RDS"))

wave_2_speeches_ethnicity_yhat_dfs <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_ethnicity_yhat_dfs.RDS"))
```

```{r}
# compute pseudo R2 for each model 
# this takes some time to run

wave_2_lyrics_R2s <- list(
  lmer = performance::r2_nakagawa(wave_2_lyrics_mods$lmer), 
  clmm = performance::r2_nakagawa(wave_2_lyrics_mods$clmm), 
  glmer = performance::r2_nakagawa(wave_2_lyrics_mods$glmer))

saveRDS(wave_2_lyrics_R2s, here("_data", "_intermediary_data", "models", "wave_2_lyrics_R2s.RDS"))

wave_2_speeches_R2s <- list(
  lmer = performance::r2_nakagawa(wave_2_speeches_ethnicity_mods$lmer), 
  clmm = performance::r2_nakagawa(wave_2_speeches_ethnicity_mods$clmm), 
  glmer = performance::r2_nakagawa(wave_2_speeches_ethnicity_mods$glmer))

saveRDS(wave_2_speeches_R2s, here("_data", "_intermediary_data", "models", "wave_2_speeches_R2s.RDS"))
```

```{r}
wave_2_lyrics_R2s  <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_lyrics_R2s.RDS"))

wave_2_speeches_R2s  <- readRDS(here("_data", "_intermediary_data", "models", "wave_2_speeches_R2s.RDS"))
```

```{r}
r2_gt <- bind_rows(

  wave_2_lyrics_R2s |> 
    bind_rows(.id = "model") |>
    mutate(text = "lyrics"),
  
  wave_2_speeches_R2s |>
    bind_rows(.id = "model") |>
    mutate(text = "speeches")) |>
  
  
  gt(groupname_col = "text", rowname_col = "model") |>
  
  tab_header(
    title = md("$R^2$ by Model, by Text Type")) |>
  fmt_number(columns = c(R2_marginal, R2_conditional), decimals = 3) |>
  cols_label(
    R2_marginal = md("$R^2_{marginal}$"),
    R2_conditional = md("$R^2_{conditional}$")
  )


gtsave(r2_gt, here("tables", "main_r2_table.tex"), as_latex = TRUE)

```


```{r}
plot_observed_predicted <- function(df_list, r2_list) {
  
  plots <- lapply(names(df_list), function(model_name) {
    
    df <- df_list[[model_name]]
    
    # Marginal R2 (variance explained by fixed effects only)
    r2_marginal <- round(r2_list[[model_name]]$R2_marginal, 3)
    
    # Conditional R2 (variance explained by fixed and random effects)
    # r2_conditional <- round(r2_list[[model_name]]$R2_conditional, 3)
    
    ggplot(df, aes(as.factor(y), yhat)) +
      geom_boxplot() +
      geom_abline(intercept = -2, slope = 1, color = "red") +
      scale_y_continuous(
        limits = c(-2, 9),
        breaks = seq(-2, 9, 1)
      ) +
      labs(
        #title = paste0(model_name, ":  R² = ", r2_marginal), 
        title = model_name, 
        x = "Observed rating", y = "Predicted rating") +
      theme_minimal(base_size = 12)
  })
  
  names(plots) <- names(df_list)
  return(plots)
}

```


```{r}
merge_yhat_plots <- function(yhat_plot_list, name){
  
  # remove ticks from plots
  p1 <- yhat_plot_list[[1]] 
  
  p2 <- yhat_plot_list[[2]] + 
    theme(axis.title.y = element_blank(),
          axis.text.y  = element_blank(),
          axis.ticks.y = element_blank())

  p3 <- yhat_plot_list[[3]] + 
    theme(axis.title.y = element_blank(),
          axis.text.y  = element_blank(),
          axis.ticks.y = element_blank())
  
  (p1 + p2 + p3) + 
    plot_layout(guides = "collect") + 
    plot_annotation(title = paste0(name, ":"))
}
```

```{r}
wave_2_lyrics_yhat_plots <- plot_observed_predicted(
  df_list = wave_2_lyrics_yhat_dfs,
  r2_list = wave_2_lyrics_R2s)

merge_yhat_plots(wave_2_lyrics_yhat_plots, name = "Lyrics")

ggsave(here("images", "main_lyrics_yhat_plots.pdf"))
```

```{r}
wave_2_speeches_ethnicity_yhat_plots <- plot_observed_predicted(
  df_list = wave_2_speeches_ethnicity_yhat_dfs,
  r2_list = wave_2_speeches_R2s)

merge_yhat_plots(wave_2_speeches_ethnicity_yhat_plots, name = "Speeches")

ggsave(here("images", "main_speeches_yhat_plots.pdf"))
```
