---
title: "R Notebook"
---

```{r}
library("here")             # file logistics
library("tidyverse")        # code logistics
library("emmeans")          # estimated marginal means
library("RobustRankAggreg") # rank aggregation
library("patchwork")        # merge plots
library("gt")               # latex tables
library("viridis")          # colors

options(scipen = 999)
```

```{r}
# read in data
wave_2_dfs <- readRDS(here("_data", "_intermediary_data", "wave_2_dfs.RDS"))

df <- bind_rows(
  wave_2_dfs[['wave_2_lyrics']] |> 
    select(item_ID, participant_ID, value, rating), 
  wave_2_dfs[['wave_2_speeches']] |> 
    select(item_ID, participant_ID, value, rating), 
  .id = "text") |>
  
  mutate(text = case_when(
    text == "1" ~ "lyrics", 
    text == "2" ~ "speeches"))


lyrics_df <- readRDS(here("_data", "_primary_data", "lyrics_df.RDS"))
```

```{r}
lyrics_rank_df <- df |>
  filter(text == "lyrics") |>
  filter(!is.na(rating)) |>
  group_by(item_ID, participant_ID) |>
  filter(n() > 1) |>
  mutate(rank = dense_rank(-rating)) |>
  arrange(rank, .by_group = TRUE) |>
  summarise(
    ranking = list(as.character(value)),
    .groups = "drop") |>
  left_join(
    lyrics_df |> 
      mutate(item_ID = as.character(item_ID)) |>
      select(item_ID, artist_topic_bin_labels), 
      by = "item_ID")
```

```{r}
rra_lyrics <- bind_rows(
  
  # ranking from the top
  lyrics_rank_df |> 
    group_by(item_ID) |>
    group_modify(~ {
  
      if (nrow(.x) < 2) {return(tibble())}
  
      rra <- aggregateRanks(.x$ranking,method = "RRA", exact = T)
  
      rra |>
        rename(value = Name) |>
        mutate(direction = "top")}) |>
    ungroup(),

  # ranking from the bottom
  lyrics_rank_df |>
    group_by(item_ID) |>
    group_modify(~ {
  
      if (nrow(.x) < 2) {return(tibble())}
  
      rra <- aggregateRanks(
        lapply(.x$ranking, rev),
        method = "RRA")
  
      rra |>
        rename(value = Name) |>
        mutate(direction = "bottom")}) |>
    ungroup()) |>
  
  mutate(agree = ifelse(Score < .05, 1, 0)) |>
  
  left_join(
    lyrics_df |> 
      mutate(item_ID = as.character(item_ID)) |>
      select(item_ID, artist_topic_bin_labels), 
    by = "item_ID")
```

```{r}
magma_col <- viridis(10, option = "magma")[6]

lyrics_plot_df <- rra_lyrics |>
  group_by(item_ID, artist_topic_bin_labels) |>
  summarise(agreement = sum(agree), .groups = "drop") |>
  count(agreement) |>
  mutate(prop = n / sum(n))

p1 <- ggplot(lyrics_plot_df, aes(x = agreement, y = n)) +
  geom_col(color = "black", fill = magma_col, alpha = .7) +
  geom_text(
    aes(label = scales::percent(prop, accuracy = .1)),
    vjust = -0.4,
    size = 3) +
  scale_x_continuous(limits = c(-.5, 7.5), breaks = 0:7) +
  xlab("Number of Identified Values per Song") +
  ylab("Number of songs") +
  theme_classic()

#p1
```

```{r}
lyrics_agreement_per_item_genre <- rra_lyrics |>
  
  group_by(artist_topic_bin_labels, item_ID) |>
  summarise(
    n_values_identified = sum(agree),
    .groups = "drop")

lyrics_agreement_dist_genre <- lyrics_agreement_per_item_genre |>
  group_by(artist_topic_bin_labels, n_values_identified) |>
  summarise(n = n(), .groups = "drop") |>
  group_by(artist_topic_bin_labels) |>
  mutate(prop = n / sum(n)) |>
  group_by(artist_topic_bin_labels) |>
  summarise(
    median_identified = median(n_values_identified),
    .groups = "drop") |>
  arrange(desc(median_identified))

gt_lyrics_agreement <- lyrics_agreement_dist_genre |>
  gt(rowname_col = "artist_topic_bin_labels") |>
  cols_label(median_identified = "Median number of values identified") |>
  fmt_number(
    columns = median_identified,
    decimals = 1) |>
  tab_header(
    title = "Value Agreement in Lyrics by Genre") |>
  tab_source_note(
    source_note = "Note. Values indicate the median number of values consistently identified by robust rank aggregation (RRA) per song.")

gt_lyrics_agreement

gtsave(gt_lyrics_agreement, filename = here("tables", "main_lyrics_RRA_by_genre.tex"))
```

```{r}
lyric_genre_rra_df <- bind_rows(
  
  lyrics_rank_df |>
    group_by(artist_topic_bin_labels) |>
    group_modify(~ {
      
      if (nrow(.x) < 2) {return(tibble())}
      
      rra <- aggregateRanks(.x$ranking,method = "RRA", exact = F)
      
      rra |>
        rename(value = Name) |>
        mutate(direction = "top")}), 
  
  lyrics_rank_df |>
    group_by(artist_topic_bin_labels) |>
    group_modify(~ {
      
      if (nrow(.x) < 2) {return(tibble())}
      
      rra <- aggregateRanks(
        lapply(.x$ranking, rev),
        method = "RRA", exact = F)
      
      rra |>
        rename(value = Name) |>
        mutate(direction = "bottom")}) |>
    ungroup()) |>
  mutate(agree = Score < 0.05)
```

```{r}
lyric_genre_rra_df <- lyric_genre_rra_df |> 
  
  select(
    artist_topic_bin_labels, 
    value,
    direction,
    Score,
    agree) |>
  
  pivot_wider(
    names_from  = direction,
    values_from = c(Score, agree),
    names_sep   = "_") |>
  
  filter(Score_top <= .05 | Score_bottom <= .05) |>
  
  mutate(
    salience = case_when(
      agree_top    ~   1 - Score_top,
      agree_bottom ~ -(1 - Score_bottom),
      TRUE         ~   0))
```

```{r}
magma_col <- viridis(10, option = "magma")

value_order <- lyric_genre_rra_df |>
  group_by(value) |>
  summarize(mean_salience = mean(salience)) |>
  arrange(desc(mean_salience)) |>
  pull(value)

lyric_genre_rra_df |>
  mutate(value = factor(value, levels = value_order)) |>
  
  mutate(
    salience_dir = case_when(
      salience > 0 ~ "Top",
      salience < 0 ~ "Bottom",
      TRUE         ~ NA_character_)) |>

  ggplot(aes(x = artist_topic_bin_labels, y = value, fill = salience_dir)) +
    geom_tile(color = "white", linewidth = 0.3) +
    scale_fill_manual(
      values = c(
        "Bottom"  = magma_col[3],
        "Top"     = magma_col[6]),
      breaks = c("Top", "Bottom"),
      name = "Rank Placement") +
  
    labs(x = "Genre", y = "Value", title = "Salient Values by Genre") +
    theme_classic() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1), 
      plot.title = element_text(hjust = 0.5),
      legend.position = "right") +  coord_flip()

ggsave(here("images", "main_lyrics_RRA_genre.pdf"))
```

```{r}
speeches_rank_df <- df |>
  filter(text == "speeches") |>
  filter(!is.na(rating)) |>
  group_by(item_ID, participant_ID) |>
  filter(n() > 1) |>
  mutate(rank = dense_rank(-rating)) |>
  arrange(rank, .by_group = TRUE) |>
  summarise(
    ranking = list(as.character(value)),
    .groups = "drop") |>
  left_join(
    wave_2_dfs[["wave_2_speeches"]]|>select(participant_ID, Ethnicity, spectrum)|>unique(),
    by = "participant_ID")
```


```{r}
rra_speeches <- bind_rows(
  
  # ranking from the top
  speeches_rank_df |> 
    group_by(item_ID) |>
    group_modify(~ {
  
      if (nrow(.x) < 2) {return(tibble())}
  
      rra <- aggregateRanks(.x$ranking,method = "RRA", exact = F)
  
      rra |>
        rename(value = Name) |>
        mutate(direction = "top")}) |>
    ungroup(),

  # ranking from the bottom
  speeches_rank_df |>
    group_by(item_ID) |>
    group_modify(~ {
  
      if (nrow(.x) < 2) {return(tibble())}
  
      rra <- aggregateRanks(lapply(.x$ranking, rev),method = "RRA")
  
      rra |>
        rename(value = Name) |>
        mutate(direction = "bottom")}) |>
    ungroup()) |>
  
  mutate(agree = ifelse(Score < .05, 1, 0))
```

```{r}
viridis_col <- viridis(10, option = "D")[6]

plot_df <- rra_speeches |>
  group_by(item_ID) |>
  summarise(agreement = sum(agree), .groups = "drop") |>
  count(agreement) |>
  mutate(prop = n / sum(n))

p2 <- ggplot(plot_df, aes(x = agreement, y = n)) +
  geom_col(color = "black", fill = viridis_col, alpha = .7) +
  geom_text(
    aes(label = scales::percent(prop, accuracy = .1)),
    vjust = -0.4,
    size = 3) +
  scale_x_continuous(limits = c(-.5, 7.5), breaks = 0:7) +
  xlab("Number of Identified Values per Speech") +
  ylab("Number of Speeches") +
  theme_classic()

#p2
#ggsave(here("images", "main_speeches_RRA.pdf"), height = 5, width = 7)
```

```{r}
(p1 | p2) + plot_annotation(tag_levels = "A")

ggsave(here("images", "main_values_RRA.pdf"), height = 5, width = 8)
```


```{r}
run_rra_by_group <- function(df) {

  df <- df |>
    # merge ethnicity and spectrum into a single variable
    mutate(group = paste(Ethnicity, spectrum, sep = " · "))

  bind_rows(
    # top
    df |>
      group_by(group) |>
      group_modify(~ {
        if (nrow(.x) < 2) return(tibble())
        
        rra <- aggregateRanks(.x$ranking, method = "RRA", exact = FALSE)
        rra |>
          rename(value = Name) |>
          mutate(direction = "top")}) |>
          ungroup(),

    # bottom
    df |>
      group_by(group) |>
      group_modify(~ {

        if (nrow(.x) < 2) return(tibble())

        rra <- aggregateRanks(lapply(.x$ranking, rev), 
                              method = "RRA",exact = FALSE)
        rra |>
          rename(value = Name) |>
          mutate(direction = "bottom")}) |>
        ungroup()
)}
```

```{r}
# add in party labels
speeches_rank_df <- speeches_rank_df |> 
  left_join(
    wave_2_dfs[["wave_2_speeches"]] |> 
      select(item_ID, party) |> 
      unique(), 
    by = "item_ID")

# estimate RRA separately for each party being rated
rra_speeches_by_party <- lapply(
  split(speeches_rank_df, speeches_rank_df$party),
  run_rra_by_group
)
```

```{r}
# set value order according to the first dataframe
value_order <- rra_speeches_by_party[[1]] |>
  
  mutate(agree = Score < .05) |>
  select(group,value, direction, Score, agree) |>
  pivot_wider(
    names_from  = direction,
    values_from = c(Score, agree),
    names_sep   = "_") |>
  
  filter(Score_top <= .05 | Score_bottom <= .05) |>
  
  mutate(
    salience = case_when(
      agree_top == 1    ~   1 - Score_top,
      agree_bottom == 1 ~ -(1 - Score_bottom),
      TRUE              ~   0)) |>
  
  group_by(value) |>
  summarise(mean_salience = mean(salience), .groups = "drop") |>
  arrange(desc(mean_salience)) |>
  pull(value)
```


```{r}
plots <- lapply(rra_speeches_by_party, function(df){
  
  # format df
  df <- df |>
    
    mutate(agree = ifelse(Score < .05, 1, 0)) |>
  
    select(group, value, direction, Score, agree) |>
    
    pivot_wider(
      names_from  = direction,
      values_from = c(Score, agree),
      names_sep   = "_")  |>
    
    filter(Score_top <= .05 | Score_bottom <= .05) |>
    
    mutate(
      salience = case_when(
        agree_top ==   1 ~   1 - Score_top,
        agree_bottom ==1 ~ -(1 - Score_bottom),
        TRUE             ~   0))
    
  # plot
  viridis_col <- viridis(10, option = "D")
  
  
  df |>
    mutate(value = factor(value, levels = value_order)) |>
    
    mutate(
      salience_dir = case_when(
        salience > 0 ~ "Top",
        salience < 0 ~ "Bottom",
        TRUE         ~ NA_character_)) |>
  
    ggplot(aes(x = group, y = value, fill = salience_dir)) +
      geom_tile(color = "white", linewidth = 0.3) +
      scale_fill_manual(
        values = c(
          "Bottom"  = viridis_col[3],
          "Top"     = viridis_col[6]),
        breaks = c("Top", "Bottom"),
        name = "Rank Placement") +
    
      labs(x = "Rater Characteristic", y = "Value", 
           title = "Salient Values by Rater Characteristic") +
      theme_classic() +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1), 
        plot.title = element_text(hjust = 0.5),
        legend.position = "right") +  coord_flip()

})
```

```{r}
(plots[[1]] / plots[[2]] ) +
  plot_annotation(tag_levels = "A")

ggsave(here("images", "main_speeches_RRA_characteristic_party.pdf"), height = 7)
```

