## Methods

### Participant Recruitment

We aimed for a ground-truth that represents the average perspective of a population, and if relevant the average perspective of a sub-group of the population. We thus used our pilot studies to estimate the number of ratings needed to approximately capture the US population mean. To see if perspectives between sub-groups of the population varied, we recruited a sample of respondents stratified by the most common ethnicities in the US according to the 2024 US Census[^02_pilot_methods-1], and additionally by political leaning (i.e. conservative, moderate, liberal) for `speeches`. We used Prolific[^02_pilot_methods-2], an online survey participant recruitment platform to draw a sample that was stratified based on information participants report at registration, according to categories determined by Prolific. For ethnicity, these were: White, Black/African American, Hispanic/Latino, and three Asian sub-categories, East Asian, South Asian, South East Asian, which we combined into a single 'Asian' category. For `speeches`, we also recruited participants stratified by political spectrum (Conservative, Moderate, Liberal). We estimated the target number of ratings separately per text type (`lyrics` / `speeches`), as we expected that each form of text could vary in terms of degree of ambiguity. We recruited a total 300 participants: 100 each stratified by ethnicity completed the `lyrics` and the first `speeches` pilot, and 100 participants stratified by political orientation completed the second `speeches` pilot.

[^02_pilot_methods-1]: https://www.census.gov/quickfacts/fact/table/US

[^02_pilot_methods-2]: prolific.com

We conducted pilot studies with the primary aim of estimating the number of ratings needed per text type (`lyrics` vs. `speeches`), following a procedure similar to @DeBruine_Jones_2018. In our case, this procedure involved bootstrapping estimates of inter-rater reliability on data comprised of a) a relatively large number of ratings, on b) a relatively small sub-sample of the items to be rated. In each pilot study, 100 participants rated 14 items (either lyric or political speech excerpts). We bootstrapped estimates of inter-rater reliability by sub-sampling numbers of raters, and then estimating a) the Pearson correlation between the sub-sample mean, and the overall sample mean, and b) inter-rater reliability [@DeBruine_Jones_2018]. We sub-sampled in increments of 5, ranging from 5 to 50, with replacement, 50 times for each increment: i.e. we sampled 5 raters 50 times, 10 raters 50 times, 15 raters 50 times etc. up to 50 raters 50 times, all with replacement. As we aim to represent the mean of a population of raters, we estimate inter-rater reliability as 'general consensus' and not 'absolute agreement' via intraclass correlation coefficient (type ICC2k), using a value of 0.75 as threshold to indicate sufficent, or "good", agreement [@koo2016guideline]. Thus, for a given number of raters, we estimate a sampling distribution representing their degree of general consensus, and whether the the mean consensus exceeds the 0.75 threshold. Although we did not see a recommended threshold for pearson correlations in [@DeBruine_Jones_2018], we set a threshold of 0.9 to indicate sufficient, or "high" correlation between sub-sample and overall sample means.

### Survey

The primary instrument in all surveys is the 10-item Short Schwartz Value Survey (SSVS) questionnaire developed by [@lindeman2005measuring], which participants completed on the Qualtrics survey platform. Each of the 10 questionnaire items in the SSVS is the name of a specific value in the Schwartz value inventory, along with a few descriptive words e.g. "POWER (social power, authority, wealth, influence on people and events)". We asked participants to read the instructions from the Schwartz Value Survey[^02_pilot_methods-3] in order to introduce the concept of personal values, and to instruct them on how to complete the questionnaire [@schwartz2005schwartz]. Participants then completed the questionnaire about themselves. The response format is a 9-point likert scale which ranges from -1 (Opposed to their values) and 0 (Not at all Important), to 6 (Very Important) and 7 (Of Supreme Importance) [@lindeman2005measuring].

[^02_pilot_methods-3]: Retrieved from https://scholarworks.gvsu.edu/orpc/vol2/iss2/9/ March, 2024

Participants completed an adapted version of the SSVS for each of the lyric or speech excerpts they rated. We used an SSVS version similar to [@demetriou2024towards], in which the instructions are slightly adapted for annotation. Firstly, we ask participants to respond to the questions while considering the Speaker, which we distinguish from the Author of the text i.e. the person or people responsible for selection of words and their structure. In the case of `speeches`, the "Speaker" was defined as the president delivering the speech, as opposed to e.g. staff who may have written it all or in part, or other individuals who occasionally appear in the speech transcript. In the case of Lyrics we explain that the Author of the lyrics may write from the perspective of someone or something else, whom we call the "Speaker". We instruct participants to respond with the Speaker of the lyrics in mind. Secondly, we present participants with a 'Not Applicable' response option, as we expect that excerpts of text give an incomplete picture of the values of the Speaker. Thus, we give participants the option to indicate "NA" to indicate "Not Applicable" if they felt no information on the value is present in the text. We thus gather 10 likert-scale responses per item (`lyric` / `speech` excerpt) being rated, within a range of -1 to 7, and with possible NAs.

A secondary instruction in our pilot included a comprehension quiz, which asked three questions shown in random order, each of which included a brief scenario: (1) "If you feel a SPEAKER seeks POWER above all else as a life-guiding principle, how would you respond?", to which the correct response was at the high end of the scale (i.e. 5, 6, or 7), (2) "If you feel a SPEAKER doesn't give any indication of how important POWER is to them in the lyrics, how would you respond?" to which a correct response was "NA", and (3) "If you feel a SPEAKER avoids POWER more than anything else, or sees it as completely unimportant to them, how would you respond?" to which a correct response was on the lower end of the scale (i.e. -1, 0, or 1). Questions were accompanied by the single item, POWER. After each question, the survey displayed the correct response, along with a brief explanation e.g. "If you feel a SPEAKER seeks POWER above all else as a life-guiding principle, respond with a '7', indicating it is of Supreme Importance to them". Participants most often mistook "NA" and low-end scale responses in Quiz items 2 and 3. Thus, for Quiz 2 where the correct response was "NA", 13% of participants indicated "0" and "9"% indicated "-1", where 56% correctly indicated "NA". Similarly in Quiz 3, 13% of participants incorrectly indicated "NA" where 50% and 20% of participants correctly indicated "-1"' and "0" respectively. Thus, in the minds of many annotators, "NA" and the lower-end of the scale bear similar meaning.

We collected a number of exploratory measures which we felt might affect participant ratings, but for which we had no specific prediction. For lyrics we asked participants "Do you think the SPEAKER and the AUTHOR are the same person?", and "Do you recognize the song that the lyrics come from?", and for speeches we asked participants "Do you recognize the president that delivered the speech?", and "Which party do you think the president belongs to?". Following the SSVS for each lyric or speech excerpt, we also assessed participant confidence in their ratings by asking "How confident are you in your ratings of these lyrics? / this speech?", to which participants could respond on a scale from 1 (Completely Confident) to 5 (Completely Unconfident).

Our survey also checked if participants were paying attention. As per Prolific guidelines, we include an attention check at the halfway point of the annotation component of the survey. The check appeared to be another song lyric, with the lyrics being instructions to participants to indicate "7" for the value of Stimulation, "0" for all other values. Participants who responded with "-1" or "NA" instead were also considered passing if they were consistent in the ratings of all values other than Stimulation. Participants who failed the attention check were returned to Prolific, and automatically replaced.

The procedure used was reviewed by the Independent Review Board at Delft University of Technology \[# etc.\]. For complete survey materials, see Supplementary Materials:Survey.

### Lyrics data

We used the same initial 2200 pool as in @demetriou2024towards, who attempted to gather a stratified sample of lyrics. An ideal scenario would have been to have a target number of songs, randomly sampled from within clearly defined strata [@groves2009survey]. @demetriou2024towards acknowledge that 1) the population of songs is enormous, with many streaming services reporting over 100M songs [^02_pilot_methods-4], and that no target sample size could be calculated, and 2) some strata affecting the use of language in song lyrics are less clear, or 'fuzzier', than others: e.g., the year of release, which may reflect different events or time-specific colloquial slang, is relatively more clear than e.g. popularity for music, although it can be estimated from various sources such as hit charts, which is more clear than genre, for which there may be some overlap in human labels, but no clear musicological taxonomy [@Liem2012MusicGap]. Thus, the target number of sampled songs was determined by budgetary limitations, and the sampled strata were acknowledged to be 'fuzzy': (1) `year`, the release date according to Musixmatch meta-data; (2) `popularity`, operationalized as the frequency with which an artist appeared on a playlist in the MPD\[@DBLP:conf/recsys/ChenLSZ18\]; (3) `genre`, estimated from topic modeling on Million Song Dataset artist tags [@schindler2012facilitating]; (4) `lyric topic`, through a bag-of-words representation of the lyrics data. Genre and lyric topic were treated as categorical variables, and popularity and year were divided into equally spaced bins, with year divided into decades (60s, 70s, 80s, and so on). When sampling,  @demetriou2024towards attempted to get as close as possible to even numbers of tracks within these 4 dimensional cells for their initial pool of 2200 songs.

[^02_pilot_methods-4]: https://en.wikipedia.org/wiki/Comparison_of_music_streaming_services

@demetriou2024towards sampled their initial pool of 2200 songs from the Million Playlist Dataset (MPD)[^02_pilot_methods-5]. The first 30% of the words of each song comprised the lyric excerpts in the initial pool, as this is how they were provided by Musixmatch[^02_pilot_methods-6], a lyrics and music language crowdsourcing platform whose members contribute, verify, sync, and translate lyrical content. Although crowdsourced lyrics may deviate from the officially authored lyrics, Musixmatch engages in steps to verify quality of content, including spam detection, formatting, spelling and translation checking, and manual verification by community curators, and a local team of Musixmatch editors. @demetriou2024towards manually screened songs to confirm that the lyrics matched the metadata of the song, selecting a total of 380 songs. Screening was conducted independently initially, and disagreements were resolved via discussion. Screening primarily confirmed that the song metadata matched the song title and artist title if searched on the internet. Screening secondarily removed songs that were (1) not in English; (2) completely onomatopoetic or nonsense; (3) comprised of single words or single phrases; (4) consisted of too few words. Authors of this work further screened songs until a total of 1200 potential songs were considered usable. The first 800 were reserved for the main study, and the last 14 were used for the pilot study. We used 14 songs from the end of the list for our pilot study, and a total of 800 songs from the beginning of the list for annotation.

[^02_pilot_methods-5]: https://research.atspotify.com/2020/09/the-million-playlist-dataset-remastered/

[^02_pilot_methods-6]: https://www.musixmatch.com/

### Speeches data

Speeches were sampled from U.S. Presidents delivering State of the Union Addresses, from the UVA Miller center repository of transcripts [^02_pilot_methods-7], and were stratified within (1) president and (2) speech. We excluded all speeches before 1900 so as to sample language that is approximately current. We then split all speeches into 52 / n chunks, where n is the number of speeches each president delivered, thus extracting the same number of chunks per president. We then extracted the first ~200 words (range 153:234) of complete sentences from each chunk, in order to avoid confusion from sentence truncation. 



[^02_pilot_methods-7]: https://millercenter.org/the-presidency/presidential-speeches
