## General Methods

Across three pilot studies and four waves of our main study, we gathered data to estimate how people perceived the values present in two forms of text: song lyrics and political speeches. We conducted pilot studies with the primary aim of estimating the number of observations for each piece of text, per text type (`lyrics` vs. `speeches`). We conducted our main study to gather perceptions of values in text more broadly, one for lyric and one for speech excerpts. We stratified our participant samples by self-reported ethnicity for both lyrics and speeches (`Asian`, `African American / Black`, ``Latino/Histpanic`, `White`), and for speeches we further stratify participants by self-reported political leaning (`Conservative`, `Moderate`, `Liberal`). We used an existing sample of lyrics roughly stratified across four strata (`year` of release, `genre`, `popularity`, and lyrical `topic`). We sampled political speeches of U.S. presidents, stratified by `president` and by `speech`. As studies generally shared the same overall procedure to recruit participants and gather observations, we herein describe the stimuli, survey design, and participant recruitment procedure. 

Our procedures were reviewed, determined to have minimal risk to participants, and thus approved by the Human Research Ethics Committee at Delft University of Technology[^10_methods-1]. The study plans and analysis were preregistered on the Open Science Framework ([https://osf.io/fhq75](https://osf.io/fhq75)).

[^10_methods-1]: Letters of approval #: 4011, 4024, 4152, & 4507

All analyses were conducted in `R` [@R-base] within the `RStudio` integrated development environment [@RStudio], along with the `here` [@here] helper functions for managing file paths. Data wrangling and statistical analysis relied on the `tidyverse` suite [@tidyverse], helper functions from `rlang` [@rlang] and `ggplot2` for visualization [@ggplot2]. Reliability analyses were conducted with the `psych` package [@psych], mixed-effects models were estimated with `lme4` [@lme4], and p values from statistical tests were estimated with `lmerTest` [@lmerTest]. Additional APA formatting and reporting used `gt` [@gt] and `papaja` [@papaja].
