### Stimuli

We aimed to gather two sets of stimuli, one each representing diverse lyrics, and political speeches. Both sets were developed using stratified sampling approaches. See Appendix A: Stimuli for further details regarding stimuli data and sampling procedures.

#### Song Lyrics

We used the same initial pool of song lyric excerpts as @demetriou2024towards, who obtained lyrics with permission via the API of Musixmatch[^11_stimuli-1]. Musixmatch crowdsources lyrics by hosting a platform where users add, correct, sync, and translate the lyrics to songs. Musixmath further engages in quality assurance which includes spam detection, formatting, checking spelling and translation, and manual verification, via their employee editors and a community of curators that function similarly to moderators on forums like Reddit.

[^11_stimuli-1]: https://www.musixmatch.com/

@demetriou2024towards aimed at gathering a diverse sample of songs using a procedure they called "fuzzy stratified sampling". An ideal scenario would have been to gather a representative sample of lyrics, with a pre-determined target number of songs, randomly sampled from within clearly defined strata [@groves2009survey]. However, @demetriou2024towards note that the population of songs is enormous, with many streaming services reporting over 100 million songs in their catalogues[^11_stimuli-2], and that no work to their (or our) knowledge has been conducted to determine a complete list of strata, or an appropriate target number of songs on which to gather perceptions of values. Further, while some strata that may relate to language use in song lyrics are conceptually clear, such as the year of release which may indicate time-appropriate slang or current events, other strata are far less clear: e.g. (1) the year of release is a conceptually clear stratum compared to (2) popularity for which no single ideal method for its estimation exists despite a plurality of approaches, which in turn is more clear than (3) genre for which there may be some overlap in human labels, but no universally agreed upon musicological taxonomy [@Liem2012MusicGap], which in turn is practically more clear than (4) the topic of the lyrics, for which topic estimation is likely to be imprecise. @demetriou2024towards thus aim for a diverse rather than a fully representative sample, by taking a stratified sampling approach while acknowledging that the strata are "fuzzy", and some important strata may be missing.

Briefly, @demetriou2024towards uniformally randomly sampled an initial pool of 60,000 artists in the Spotify Million Playlist Dataset (MPD)[^11_stimuli-3] [@chen2018recsys]. The MPD contains the metadata of approximately 2 million individual tracks from approximately 300,000 artists, as they were arranged in playlists by users. @demetriou2024towards then drew the metadata of every song from the entire discography of those 60,000 artists from the Spotify API and checked the availability of those songs in the Musixmatch database, resulting in large pool of approximately 510,000 songs from approximately 15,400 artists. Musixmatch provided the first 30% of the lyrics of each of the 510,000 songs via their API.

[^11_stimuli-2]: https://en.wikipedia.org/wiki/Comparison_of_music_streaming_services

From the pool of available 510,000 songs, @demetriou2024towards then drew a sample of 2,200 song lyrics, the number of which was determined by their budgetary limitations. Songs were sampled within four "fuzzy" music strata: (1) `year`, the release date according to Musixmatch meta-data, which might contain some errors; (2) `popularity`, operationalized as the frequency that an artist appeared on a playlist in the MPD [@chen2018recsys]; (3) `genre`, estimated from topic modeling user-generated tags of artists in the MPD [@schindler2012facilitating], which were drawn from Last.fm and merged into the MPD[^11_stimuli-4]; and (4) `lyric topic`, via topic modelling on a bag-of-words representation of the lyrics data. They observed a skew such that more recent and popular artists and songs appeared substantially more on playlists, and were far more likely to be sampled. Popularity had an especially severe skew. To increase sample diversity, popularity was divided into 7 ordinal bins which were approximately equal in terms of the number of songs in each bin. Year of release was divided into equally spaced ordinal bins with year being divided into decades (60s, 70s, 80s etc.), and genre and lyric topics were treated as non-ordinal categorical bins. 

[^11_stimuli-3]: https://research.atspotify.com/2020/09/the-million-playlist-dataset-remastered/
[^11_stimuli-4]: http://millionsongdataset.com/

@demetriou2024towards then manually screened songs for inclusion in the study. Screening primarily confirmed that the song metadata matched the song title and artist name if searched on the internet, and that the lyrics in the sample matched the lyrics of the song when listening to a streamed version. Screening secondarily removed songs that were (1) were more than approximately 20% non-English words or characters; (2) completely onomatopoetic or nonsense; (3) comprised of repeated single words or single phrases; or (4) consisted of too few words. @demetriou2024towards selected a total of 380 songs. We (authors of present work) further screened songs using the same requirements until a total of 1,200 songs were considered usable. The first 800 excerpts were used in the main study, and the next 14 were used for the lyrics pilot study. As some songs lyrics contained non-lyric words, indicating e.g. section (i.e. verse or chorus), artist, or time stamp, included songs were manually corrected to only contain the song lyrics. Songs most frequently removed were completely non-English or contained a large number of non-English words, e.g. reggae songs written in Jamaican Patois or k-pop / j-pop which contained words in English as well as Korean or Japanese, followed by songs that had very few or single repeated words such as dance and electronic music. 

#### Political Speeches

We chose the U.S. State of the Union addresses as the overall corpus, as the addresses are a long-running, formally recorded corpus of public speech, that has regularly been delivered to congress each year, by presidents of both parties of a two-party system. Speeches were sampled from the UVA Miller center repository[^11_stimuli-5], which maintains an archive of presidential communications, including presidential speech recordings and transcripts. Presidents generally gave a single State of the Union address each year of their presidency. Our samples were therefore stratified within (1) president, and (2) speech. We excluded all speeches before 1900 so as to sample language that is approximately current, and the single speech by Zachary Taylor so as not to oversample a single speech. Speeches were grouped by president. Within each president, every speech was divided into a proportional number of chunks, with presidents who gave fewer speeches contributing more chunks per speech and those with many speeches contributing fewer: e.g. 7 per speech from 2 term presidents, and 14 per speech from single term presidents. Each president contributed roughly the same number of chunks (M~chunks~ = 55.3). From each chunk, we then sampled from the 200th word to the end of the sentence it was in. 328 excerpts were then randomly selected, 44.8% of which were from Democratic presidents (M~excerpts~ = 16) vs. 55.2% Republican presidents (M~excerpts~ = 15). The first 300 were used in the main study, and 14 each were used in two pilot studies. 

[^11_stimuli-5]: https://millercenter.org/the-presidency/presidential-speeches



