### Participants

We aimed to gather responses that approximate the average perspective of a target population, and possibly sub-groups of that population, of the values present in text. We chose the United States as the target population, given that lyrics are in almost all the most popular songs in the US[^13_participants-3], and that the US presidents are likely familiar to US residents, as are the language and topics discussed. Across all studies, participants were recruited using online survey participant recruitment platform Prolific[^13_participants-2], to draw a sample that was stratified based on information participant self-reported demographics at registration, according to categories determined by Prolific. We exclusively drew participants who reported residing in the United States, and that were fluent in English. To see if perspectives between sub-groups of the population varied, our sample of respondents was stratified by the 2024 US Census[^13_participants-1] most common ethnicities: (`Asian`, `African American / Black`, ``Latino/Histpanic`, `White`). The options Prolific provided for specific ethnicity that were closest to the ethnicities listed in the US Censues were: White, Black/African American, Hispanic/Latino, and three Asian sub-categories, East Asian, South Asian, South East Asian, which we combined into a single 'Asian' category. We then aimed to recruit approximately equal numbers in each category. For perspectives on `speech` excerpts, we additionally stratified our samples by political leaning: (`Conservative`, `Moderate`, `Liberal`). 

[^13_participants-1]: https://www.census.gov/quickfacts/fact/table/US

[^13_participants-2]: prolific.com

[^13_participants-3]: https://faroutmagazine.co.uk/how-many-number-one-instrumental/?utm_source=chatgpt.com
