## Pilot Results

```{r include=FALSE}
library('here')       # file logistics
library("tidyverse")  # code logistics
library("patchwork")  # merge plots
library("gt")         # markdown
library("rlang")
library("ggtext")     # text plots
```

```{r include=FALSE} 
# read in data
file_path <- here("_data", "_intermediary_data", "bootstrapped_ICC")

# summary dfs
pilot_2_likert_summary_dfs   <- readRDS(here(file_path, "pilot_2_likert_summary_dfs.RDS"))

# text type sampled by row
pilot_2_lyrics_by_row_dfs    <- readRDS(here(file_path, "pilot_2_lyrics_by_row_dfs.RDS"))
pilot_2_speeches1_by_row_dfs <- readRDS(here(file_path, "pilot_2_speeches1_by_row_dfs.RDS"))
pilot_2_speeches2_by_row_dfs <- readRDS(here(file_path, "pilot_2_speeches2_by_row_dfs.RDS"))

rm(file_path)
```

```{r include=FALSE}
# apa formatting
theme_apa <- function(base_size = 12, base_family = "sans") {
  theme_minimal(base_size = base_size, base_family = base_family) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black"),
      axis.ticks = element_line(color = "black"),
      axis.title = element_text(size = base_size, face = "plain"),
      axis.text = element_text(size = base_size * 0.9),
      legend.position = "none",
      legend.title = element_text(face = "plain"))}
```

```{r include=FALSE}
# plot ICC2k and 95% CI by value
plot_summary_by_metric <- function(df, metric, metric_lower, metric_upper, option) {
  
  subsets <- as.list(df$subset%>%unique())
  
  lapply(subsets, function(sub){
    df %>%
      filter(subset == str_wrap(sub)) %>%
      ggplot(aes(y=value, x={{metric}}, color = value)) +
      geom_point() +
      geom_errorbar(aes(xmin = {{metric_lower}}, xmax = {{metric_upper}})) +
      geom_vline(xintercept = 0.75, color = "red", size = .4, linetype = "dashed" )+
      xlim(-.5, 1) +
      scale_color_viridis_d(option = option) +
      theme(legend.position="none",
            plot.title = element_text(size = 10, hjust = 0.0)) +
      labs(x = "ICC[2,k]",y = "Value") +
      ggtitle(label = stringr::str_wrap(sub, width = 15)) +
      theme_apa()
    })}

# density plot of bootstrapping procedure
plot_raters <- function(df, metric, name, option){
  df %>%
    ggplot(aes(x = {{metric}}, color = as.factor(n))) +
    geom_line(stat = "density", alpha = .5, size = .75) +
    xlim(0, 1) + ylim(0,10) +
    scale_color_viridis_d(option = option, direction = -1) +
    labs(color = "Rater n\n") +  
    ylab("Density") +
    xlab({{name}}) +
    theme_apa() +
    theme(legend.position = "right") +
    guides(color = guide_legend(nrow = 3))
  }
```


### Estimating the number of raters

```{r warning=FALSE, fig.width=6.5}
p1 <- plot_raters(
  pilot_2_lyrics_by_row_dfs[[1]] %>% filter(n <= 25), 
  metric = r, "Pearson's r", option = "plasma") + 
  geom_vline(xintercept = 0.9, color = "red", size = .4, linetype = "dashed") 

p2 <- plot_raters(
  pilot_2_lyrics_by_row_dfs[[1]] %>% filter(n <= 25), 
  metric = ICC2k, "ICC(2,k)", option = "plasma") +
  geom_vline(xintercept = 0.75, color = "red", size = .4, linetype = "dashed") 

figure_2a <- (p1 /p2) + 
  plot_annotation(tag_levels = 'A') +
  plot_layout(guides = "collect") &
  
  theme(legend.position = "bottom",
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

figure_2a
```

```{r warning=FALSE, echo=FALSE}
p1 <- plot_raters(
  pilot_2_speeches1_by_row_dfs[[1]] %>% filter(n >= 25), 
  metric = r, "Pearson's r", option = "viridis") + 
  geom_vline(xintercept = 0.9, color = "red", size = .4, linetype = "dashed")

p2 <- plot_raters(
  pilot_2_speeches1_by_row_dfs[[1]] %>% filter(n >= 25), 
  metric = ICC2k, "ICC(2,k)", option = "viridis") +
  geom_vline(xintercept = 0.75, color = "red", size = .4, linetype = "dashed")

figure_2b <- (p1 /p2) +
  plot_annotation(tag_levels = 'A') &
  
  theme(legend.position = "bottom",
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

figure_2b
```

```{r warning=FALSE, echo=FALSE}
p1 <- plot_raters(
  pilot_2_speeches2_by_row_dfs[[1]] %>% filter(n >= 25), 
  metric = r, "Pearson's r", option = "viridis") + 
  geom_vline(xintercept = 0.9, color = "red", size = .4, linetype = "dashed")

p2 <- plot_raters(
  pilot_2_speeches2_by_row_dfs[[1]] %>% filter(n >= 25), 
  metric = ICC2k, "ICC(2,k)", option = "viridis") +
  geom_vline(xintercept = 0.75, color = "red", size = .4, linetype = "dashed")

figure_2c <- (p1 /p2) +
  plot_annotation(tag_levels = 'A') &
  
  theme(legend.position = "bottom",
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

figure_2c
```

```{r include=FALSE, warning=FALSE, fig.width=6.5}
# figure_3 <- (figure_3a  | figure_3b) +  
#   plot_layout(guides = "collect") +
#   plot_annotation(tag_levels = 'A') &
#   theme(legend.position = "bottom")

#ggsave(here("images", "figure_3.pdf"),figure_3)
```

```{r}
right_group <- (figure_2b | figure_2c) +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom",
        legend.justification = "center")


figure <- (figure_2a| right_group) +
  # relative size of each plot
  plot_layout(widths = c(.8, 2)) +  
  plot_annotation(tag_levels = 'A')

figure

ggsave(here("images", "figure_2.pdf"),figure)
```


### Exploring annotator sample strata

```{r include=FALSE}
# compute plots
pilot_2_lyrics_agreement_plots <- plot_summary_by_metric(
  pilot_2_likert_summary_dfs[[1]], 
  ICC2k, ICC2k_lower, ICC2k_upper, 
  option = "plasma")

pilot_2_speeches1_agreement_plots <- plot_summary_by_metric(
  pilot_2_likert_summary_dfs[[2]], 
  ICC2k, ICC2k_lower, ICC2k_upper, 
  option="viridis")

pilot_2_speeches2_agreement_plots <- plot_summary_by_metric(
  pilot_2_likert_summary_dfs[[3]], 
  ICC2k, ICC2k_lower, ICC2k_upper, 
  option = "viridis")
```

```{r}
p1 <- pilot_2_lyrics_agreement_plots[[1]] 

p1 <- p1 + 
  ggtitle("Overall") +
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

p1
```

```{r}
p1_1 <- pilot_2_lyrics_agreement_plots[[2]]
p1_2 <- pilot_2_lyrics_agreement_plots[[3]]
p1_3 <- pilot_2_lyrics_agreement_plots[[4]]
p1_4 <- pilot_2_lyrics_agreement_plots[[5]]


p2 <- (p1_1 | p1_2) / (p1_3 | p1_4) +
  
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

p2 
```
```{r include=FALSE}
figure_3 <- p1 / p2

ggsave(here("images", "figure_3.pdf"), height=8.5)
```

```{r}
p1 <- pilot_2_speeches1_agreement_plots[[1]]+ggtitle("")

p1 <- p1 + 
  ggtitle("Overall") +
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

p1
```

```{r}
p1_1 <- pilot_2_speeches1_agreement_plots[[2]]
p1_2 <- pilot_2_speeches1_agreement_plots[[3]]
p1_3 <- pilot_2_speeches1_agreement_plots[[4]]
p1_4 <- pilot_2_speeches1_agreement_plots[[5]]


p2 <- (p1_1 | p1_2) / (p1_3 | p1_4) +
  
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

p2 
```

```{r include=FALSE}
figure_4 <- p1 / p2

ggsave(here("images", "figure_4.pdf"), height=8.5)
```

```{r}
p1 <- pilot_2_speeches2_agreement_plots[[1]]+ggtitle("")

p1 <- p1 + 
  ggtitle("Overall") +
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

p1
```

```{r}
p1_1 <- pilot_2_speeches2_agreement_plots[[2]]
p1_2 <- pilot_2_speeches2_agreement_plots[[3]]
p1_3 <- pilot_2_speeches2_agreement_plots[[4]]
p1_4 <- patchwork::plot_spacer()

p2 <- ((p1_1 / p1_2) | (p1_3 / p1_4)) +
  
  theme(plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

p2
```

```{r include=FALSE}
figure_5 <- p1 / p2

ggsave(here("images", "figure_5.pdf"), height=8.5)
```


### Exploring Quiz Results

```{r include=FALSE, warning=FALSE, echo=FALSE}
pilot_2_dfs <- readRDS(file = here("_data", "_participant_scores", "wave_2", "pilot_2_dfs.RDS"))


# subset pilot dfs
quiz_dfs <- lapply(pilot_2_dfs, function(df){
 
  df |>
    select(participant_ID, 
           Quiz1_1, Quiz2_1, Quiz3_1, 
           Quiz1, Quiz2, Quiz3) |>
    
    unique() |>
    
    # recalculate Quiz 3
    mutate(Quiz3 = case_when(
      Quiz3_1 == "-1" | Quiz3_1 == "0" | Quiz3_1 == "1"  ~ "1", 
      .default = "0")) |>
    
    # convert to numeric
    mutate(
      Quiz1 = as.numeric(Quiz1), 
      Quiz2 = as.numeric(Quiz2), 
      Quiz3 = as.numeric(Quiz3)) |>
    
    mutate(
      Quiz1_1 = ifelse(is.na(Quiz1_1), "NA", as.character(Quiz1_1)),
      Quiz1_1 = factor(Quiz1_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      Quiz2_1 = ifelse(is.na(Quiz2_1), "NA", as.character(Quiz2_1)),
      Quiz2_1 = factor(Quiz2_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE),
      Quiz3_1 = ifelse(is.na(Quiz3_1), "NA", as.character(Quiz3_1)),
      Quiz3_1 = factor(Quiz3_1, levels = c("NA","-1","0","1","2","3","4","5","6","7"), ordered = TRUE)
)})

apa_theme <- 
  theme_classic(base_size = 12, base_family = "sans") +
  theme(
    axis.title = element_text(size = 12),
    axis.text  = element_text(size = 10),
    legend.position = "bottom",          
    legend.title = element_text(size = 11),
    legend.text  = element_text(size = 10),
    panel.border = element_blank(),      
    axis.line = element_line(color = "black"),
    strip.background = element_blank(),  
    strip.text = element_text(size = 11)
  )

df <- bind_rows(quiz_dfs, .id = "Pilot")
```

```{r}
summarize_study <- function(df) {
  df %>%
    summarise(
      Q1 = sprintf("%d (%.1f%%)", sum(Quiz1, na.rm = TRUE),
                      mean(Quiz1, na.rm = TRUE) * 100),
      Q2 = sprintf("%d (%.1f%%)", sum(Quiz2, na.rm = TRUE),
                      mean(Quiz2, na.rm = TRUE) * 100),
      Q3 = sprintf("%d (%.1f%%)", sum(Quiz3, na.rm = TRUE),
                      mean(Quiz3, na.rm = TRUE) * 100)
    ) %>%
    
    pivot_longer(everything(), names_to = "Question", values_to = "N_percent")
}

table_4 <- lapply(quiz_dfs, summarize_study) %>%
  
  bind_rows(.id = "Study") %>%
  
  pivot_wider(names_from = Study, values_from = N_percent) %>%
  
  gt() %>%
  
  tab_header(
    title = md("**Table 4**"),
    subtitle = md("*Pilot Studies: Quiz Item Correctness*")
  ) %>%
  cols_label(
    Question = "Item",
    lyrics = "Pilot: Lyrics",
    speeches1 = "Pilot: Speeches 1",
    speeches2 = "Pilot: Speeches 2"
  ) %>%
  cols_align(
    align = "center",
    columns = everything()
  ) %>%
  cols_width(everything() ~ px(100)) |>
  tab_options(
    table.font.size = 12,
    heading.align = "left",
    table.border.top.width = px(0),       # remove top rule
    table.border.bottom.width = px(0),    # remove bottom rule
    table_body.hlines.width = px(0),   # removes horizontal lines inside body
    table_body.vlines.width = px(0)    # removes vertical lines
  ) %>%
  tab_source_note(
    
    md("*Note.* Entries are number and percentage of participants who answered correctly. Quiz responses were not used to exclude participants in pilot studies."))

table_4

#gtsave(table_4, here("tables", "table_4.tex"))
```

```{r include=FALSE}
plot_bars <- function(df, column1, column2, option) {
  
  df |> 
    mutate({{column2}} := fct_recode(as.factor({{column2}}), 
                                     "Correct"   = "1","Incorrect" = "0")) |>
        
    ggplot(aes({{column1}}, fill = as.factor({{column2}}))) + 
    geom_bar() +
    scale_fill_viridis_d(option = option,
                         name = "Response:") +
    
    scale_x_discrete(drop = FALSE)}
```

```{r}
p1 <- plot_bars(df, Quiz1_1, Quiz1, option = "D") +
  xlab("Q1 Responses") + ylab("Count") +
  apa_theme

p2 <- plot_bars(df, Quiz2_1, Quiz2, option = "D") +
  xlab("Q2 Responses") + ylab("Count") +
  apa_theme

p3 <- plot_bars(df, Quiz3_1, Quiz3, option = "D") +
  xlab("Q3 Responses") + ylab("") +
  apa_theme

(p1 | p2 | p3) +
  plot_layout(guides = "collect") &     
  theme(legend.position = "bottom", 
        plot.title = element_markdown(hjust = 0), 
        plot.subtitle = element_markdown(hjust = 0), 
        plot.caption = element_markdown(hjust = 0))

ggsave(here("images", "figure_6.pdf"))
```

```{r}
plot_stacked_bars <- function(df, column, option) {
  
  df |>
    ggplot(aes({{column}}, fill = as.factor(Pilot))) + 
    geom_bar() +
    scale_fill_viridis_d(
      option = option,
      name = "Pilot Study: ",
      labels = c("lyrics" = "Lyrics", 
                 "speeches1"  = "Speeches #1", 
                 "speeches2"  = "Speeches #2")) +
    scale_y_continuous(limits = c(0, 225)) +
    scale_x_discrete(drop = FALSE)
}
```

```{r echo=FALSE}
p1 <- plot_stacked_bars(df, Quiz1_1, option = "C") +
  xlab("Q1 Responses") + ylab("Count") +
  apa_theme

p2 <- plot_stacked_bars(df, Quiz2_1, option = "C") +
  xlab("Q2 Responses") + ylab("Count") +
  apa_theme

p3 <- plot_stacked_bars(df, Quiz3_1, option = "C") +
  xlab("Q3 Responses") + ylab("") +
  apa_theme

(p1 | p2 | p3) +
    plot_layout(guides = "collect") &
    # plot_annotation(
    #   title = "**Figure 10**",
    #   subtitle = "*Participant Quiz Responses*", 
    #   caption = md("*Note*. Bars represent raw counts of responses, including NA as a category, for all participants that answered incorrectly.<br> Colors represent specific pilot study. Correct response for Q1 was 5, 6,or 7. Correct response for Q2 was NA. <br> Correct response for Q3 was -1, 0, or 1.")) &
    theme(legend.position = "bottom", 
          plot.title = element_markdown(hjust = 0), 
          plot.subtitle = element_markdown(hjust = 0), 
          plot.caption = element_markdown(hjust = 0))

ggsave(here("images", "figure_C1.pdf"))
```

