# Appendix C: Pilot Study Addendum

```{r, include=FALSE}
library("here")       # file logistics
library("tidyverse")  # code logistics
library("gt")         # rendering tables
library("patchwork")
library("rlang")
library("ggtext")     # text plots
library("ggridges")   # joy plots
```

```{r, include=FALSE}
# read in pilot data
data_path <- here("_data", "_participant_scores", "wave_2")

# read in data
pilot_2_dfs <- readRDS(here(data_path, "pilot_2_dfs.RDS"))

# rename ethnicity column 
pilot_2_dfs[['speeches2']] <- pilot_2_dfs[['speeches2']] |> 
  rename(Ethnicity = `Ethnicity simplified`)
```

```{r, include=FALSE}
# format pilot data

# subset each df
pilot_2_demog_dfs <- lapply(pilot_2_dfs, function(df){
  df <- df |> 
    select(participant_ID, Age, Sex, `Ethnicity`) |> 
    unique()
  })

#re-add spectrum to speeches2 df
pilot_2_demog_dfs[['speeches2']] <- merge(
  
  pilot_2_demog_dfs[['speeches2']],
  
  pilot_2_dfs[['speeches2']] |> 
    select(participant_ID, `Political spectrum (us)`) |> 
    unique(), 
  
  by = "participant_ID", all.x=T)

rm(pilot_2_dfs)


# convert age to numeric
pilot_2_demog_dfs <- lapply(
  pilot_2_demog_dfs, 
  function(df){df|>mutate(Age = as.numeric(Age))})

# recode Asian ethnicity
pilot_2_demog_dfs[["lyrics"]] <- pilot_2_demog_dfs[["lyrics"]] |> 
  mutate(Ethnicity = case_when(
    Ethnicity == "East Asian" | Ethnicity == "South East Asian" | Ethnicity == "South Asian" ~ "Asian", 
    .default = Ethnicity))

pilot_2_demog_dfs[["speeches1"]]<- pilot_2_demog_dfs[["speeches1"]] |> 
  mutate(Ethnicity = case_when(
    Ethnicity == "East Asian" | Ethnicity == "South East Asian" | Ethnicity == "South Asian" ~ "Asian", 
    .default = Ethnicity))

pilot_2_demog_dfs[["speeches2"]] <- pilot_2_demog_dfs[["speeches2"]] |> mutate(Ethnicity = case_when(
  Ethnicity == "DATA_EXPIRED" ~ NA, 
  .default = Ethnicity
))

# study labels
pilot_labels <- c(
  lyrics     = "Pilot 1 (Lyrics)",
  speeches1  = "Pilot 2 (Speeches: Ethnicity)",
  speeches2  = "Pilot 3 (Speeches: Political)")
```



```{r}
table <- pilot_2_demog_dfs[[3]] |> 
    count(Ethnicity) %>%
    mutate(
      pct = 100 * n / sum(n),
      value = paste0(n, " (", round(pct, 1), "%)")) |> 
  select(Ethnicity, value) |>
  
  gt() |>
  
  cols_label(Ethnicity = "Ethnicity (Simplified)", value = "N (%)") |>
  cols_align(align = "center", columns = c(Ethnicity, value))

table

gtsave(table, here("tables", "pilot_ethnicity_speeches2.tex"))

rm(table)
```



```{r include=FALSE}
pilot_2_dfs <- readRDS(file = here("_data", "_participant_scores", "wave_2", "pilot_2_dfs.RDS"))

plot_dfs <- lapply(pilot_2_dfs, function(df){
  
  df %>% mutate(c = case_when(
    c == "Completely Confident" ~ 5, 
    c == "Somewhat Confident" ~ 4, 
    c == "Neither Confident nor Unconfident" ~ 3, 
    c == "Somewhat Unconfident" ~ 2, 
    c == "Completely Unconfident" ~ 1
  ))
})

plots <- lapply(names(plot_dfs), function(name) {
  df <- plot_dfs[[name]]
  ggplot(df, aes(x = c)) +
    geom_histogram(bins = 5) +
    theme_classic() +
    labs(title = name) +
    xlab("Confidence") + ylab("Count")
})
names(plots) <- names(plot_dfs)


p1 <- plots[['lyrics']]
p2 <- plots[['speeches1']]
p3 <- plots[['speeches2']]

pilot_confidence_plot <- (p1 | p2 | p3 )
```

```{r include=FALSE}
plot_dfs <- lapply(pilot_2_dfs, function(df){
  
  df %>% mutate(subjective = case_when(
    `subjective ` == "Completely subjective" ~ 7, 
    `subjective ` == "Very subjective" ~ 6, 
    `subjective ` == "Somewhat subjective" ~ 5, 
    `subjective ` == "Neither subjective nor objective" ~ 4, 
    `subjective ` == "Somewhat objective" ~ 3, 
    `subjective ` == "Very objective" ~ 2, 
    `subjective ` == "Completely objective" ~ 1
  ))
})

plots <- lapply(names(plot_dfs), function(name) {
  df <- plot_dfs[[name]] |> 
    select(participant_ID, subjective) |> 
    unique()
  
  ggplot(df, aes(x = subjective)) +
    geom_histogram(bins = 7) +
    theme_classic() +
    labs(title = name) +
    xlab("Subjectivity") + ylab("Count")
})
names(plots) <- names(plot_dfs)


p1 <- plots[['lyrics']]
p2 <- plots[['speeches1']]
p3 <- plots[['speeches2']]

pilot_subjectivity_plot <- (p1 | p2 | p3 )
```

```{r}
(pilot_confidence_plot / pilot_subjectivity_plot) + 
  plot_annotation(tag_levels = "A")

ggsave(here("images", "pilot_quiz_confidence.pdf"))
```

```{r include=FALSE}
df <- pilot_2_dfs[[1]] %>% 
  select(participant_ID, 
         Q1_1, # I prefer music that contains lyrics over music that does not
         Q1_2, # My favorite songs all have lyrics
         Q1_3, # I skip songs that don't have lyrics
         Q1_4, # If a song has lyrics that I don't like, I skip it
         Q1_5, # I listen to music in languages that I dont' speak
         Q1_6, # I look at the lyrics of songs in the apps of streaming services that I use
         Q2_1  # percentage of music lib
         ) %>%
  unique()

pilot_music_lib_plot <- df %>%
  ggplot(aes(x=as.numeric(Q2_1))) +
  geom_histogram(bins=10, aes(y=..density..)) +
    geom_density() +
  xlab("Music Library Percentage") + ylab("Count") + 
  theme_classic()
```

```{r include=FALSE}
 pilot_lyric_questions_plot <- df |>
  
  select(-Q2_1) |>
  pivot_longer(cols = paste0('Q1_', seq(1, 6)), 
               names_to = 'question', 
               values_to = 'response') |>
  
  mutate(response = case_when(
    response == "Strongly agree" ~ 7, 
    response == "Agree" ~ 6, 
    response == "Somewhat agree" ~ 5, 
    response == "Neither agree nor disagree" ~ 4, 
    response == "Somewhat disagree" ~ 3, 
    response == "Disagree" ~ 2, 
    response == "Strongly disagree" ~ 1)) |>
  
  mutate(question = case_when(
    question == 'Q1_1' ~ "I prefer music that contains lyrics over music that does not", 
    question == 'Q1_2' ~ "My favorite songs all have lyrics", 
    question == 'Q1_3' ~ "I skip songs that don't have lyrics", 
    question == 'Q1_4' ~ "If a song has lyrics that I don't like, I skip it", 
    question == 'Q1_5' ~ "I listen to music in languages that I dont' speak",
    question == 'Q1_6' ~ "I look at the lyrics of songs in the apps of streaming services that I use")) |>
  
  mutate(
    question = fct_reorder(question, response, .fun = median, na.rm = TRUE)) |>

  ggplot(aes(x=response, y=question, fill = question)) +
    geom_density_ridges(alpha=.8, linewidth= .3) +
    theme_classic() +
    scale_x_continuous(breaks = seq(1, 7, 1)) +
    scale_fill_viridis_d(option = "inferno") +
    scale_y_discrete(labels = function(x) str_wrap(x, width = 30), expand = expansion(mult = c(0.02, 0.35))) +
    ylab("") + xlab("Response") +
    theme(legend.position="none", axis.text.y = element_text(size = 12))
```

```{r}
(pilot_lyric_questions_plot | pilot_music_lib_plot)
```

